cshcsite/members/urls.py
""" URL routing for the Member views.
"""

from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',

    # E.g. '/members/'                  - Lists all club members. Filterable.
    url(r'^$',
        views.MemberListView.as_view(),
        name="member_list"
    ),

    # E.g. '/members/32/'               - Details of a particular member
    url(r'^(?P<pk>\d+)/$',
        views.MemberDetailView.as_view(),
        name="member_detail"
    ),

    # Ajax requests
    # E.g. '/members/23/ajax/stats/'    - Member stats are retrived asynchronously for efficiency
    url(r'^(?P<pk>\d+)/ajax/stats/$',
        views.MemberStatsView.as_view(),
        name='member_stats_ajax'),
)

cshcsite/teams/urls.py
""" URL routing for views relating to teams.
"""

from django.conf.urls import patterns, url
from teams import views, feeds


urlpatterns = patterns('',

    # E.g. '/teams/'                            - List of all CSHC teams
    url(r'^/?$',
        views.ClubTeamListView.as_view(),
        name="clubteam_list"
    ),

    # E.g. '/teams/playing-record/'             - The playing records through the seasons of each team
    url(r'^playing-record/$',
        views.PlayingRecordView.as_view(),
        name="playing_record"
    ),

    # E.g. '/teams/playing-record/ajax/'        - AJAX-only: Updates and refreshes the playing records of each team
    url(r'^playing-record/ajax/$',
        views.PlayingRecordUpdateView.as_view(),
        name="playing_record_update"
    ),

    # E.g. '/teams/southerners/'                - Statistics table comparing the performance of CSHC teams this season
    url(r'^southerners/$',
        views.SouthernersSeasonView.as_view(),
        name="southerners_league"
    ),

    # E.g. '/teams/southerners/2011-2012/'      - Statistics table comparing the performance of CSHC teams in a previous season
    url(r'^southerners/(?P<season_slug>[-\w]+)/$',
        views.SouthernersSeasonView.as_view(),
        name="southerners_league_season"
    ),

    # E.g. '/teams/southerners/2011-2012/ajax/' - AJAX-only: Updates and refreshes the Southerners statistics
    url(r'^southerners/(?P<season_slug>[-\w]+)/ajax/$',
        views.SouthernersSeasonUpdateView.as_view(),
        name="southerners_league_season_update"
    ),

    # E.g. '/teams/m1/'                         - Details of a particular CSHC team (including the team's playing record) for the current season
    url(r'^(?P<slug>[-\w]+)/$',
        views.ClubTeamDetailView.as_view(),
        name="clubteam_detail"
    ),

    # E.g. '/teams/m1/2011-2012/'               - Details of a particular CSHC team (including the team's playing record) for a previous season
    url(r'^(?P<slug>[-\w]+)/(?P<season_slug>[-\w]+)/$',
        views.ClubTeamDetailView.as_view(),
        name="clubteam_season_detail"
    ),

    # E.g. /teams/m1.ics'                       - Calendar feed of a particular team's matches
    url(r'^(?P<slug>[-\w]+).ics$',
        feeds.ClubTeamMatchICalFeed(),
        name="clubteam_ical_feed"
    ),

    # E.g. /teams/m1.rss'                       - RSS feed of a particular team's match reports
    url(r'^(?P<slug>[-\w]+).rss$',
        feeds.RssClubTeamMatchReportsFeed(),
        name="clubteam_match_rss_feed"
    ),

    # E.g. '/teams/participation/23/ajax/'      - AJAX-only: Updates and refreshes the playing record stats for a particular team in a particular season
    url(r'^participation/(?P<participation_id>\d+)/ajax/$',
        views.ParticipationUpdateView.as_view(),
        name="participation_update"
    ),

    # E.g. '/teams/m1/stats/3/ajax/'             - AJAX-only: Retrieves fixture list, league table and squad membership for a particular team/season
    url(r'^(?P<slug>[-\w]+)/stats/(?P<season_pk>\d+)/ajax/$',
        views.ClubTeamStatsView.as_view(),
        name='clubteam_stats_ajax'),

    # E.g. '/teams/m1/stats/3/ajax/scrape/'      - AJAX-only: Scrapes the external league table website and updates and refreshes the league table for a particular team/season
    url(r'^(?P<slug>[-\w]+)/stats/(?P<season_pk>\d+)/ajax/scrape/$',
        views.ScrapeLeagueTableView.as_view(),
        name='refresh_league_table'),

)

cshcsite/members/models/committee_membership.py
""" Models relating to the CSHC committee.

    CommitteePosition   - defines a particular position on the committee.
    CommitteeMembership - specifies which member held a particular CommitteePosition
                          during a particular season.
"""

from django.db import models
from django.db.models.query import QuerySet
from model_utils.managers import PassThroughManager
from competitions.models import Season
from core.models import TeamGender


class CommitteePosition(models.Model):
    """ Represents the name of a position on the committee.
    """

    name = models.CharField(max_length=100, default=None)

    gender = models.CharField("Mens/Ladies/Mixed", max_length=6, choices=TeamGender)

    index = models.PositiveSmallIntegerField("Index", default=0,
                                             help_text="Used for visual ordering of the committee")

    class Meta:
        """ Meta-info for the CommitteePosition model."""
        app_label = 'members'
        unique_together = ('gender', 'index')
        # By default, list the general committee members first, then ladies then men.
        ordering = ('-gender', 'index')

    def __unicode__(self):
        if self.gender == TeamGender.Mixed:
            return unicode(self.name)
        else:
            return unicode("{} ({})".format(self.name, self.gender))


class CommitteeMembershipQuerySet(QuerySet):
    """ Queries that relate to Committee Membership"""

    def by_member(self, member):
        """Returns only committee membership for the specified member"""
        return self.filter(member=member)

    def by_position(self, position):
        """Returns only committee membership for the specified position"""
        return self.filter(position=position)

    def by_season(self, season):
        """Returns only committee membership for the specified season"""
        return self.filter(season=season).order_by('position__index')

    def current(self):
        """ Returns only current committee membership, if any."""
        return self.filter(season=Season.current()).order_by('position__index')


class CommitteeMembership(models.Model):
    """ This model represents membership of the club committee. A member
        may hold zero or more committee positions in a particular season.

        The actual positions may vary from season to season but are captured
        in the CommitteePosition model. If a new position is created, a new
        CommitteePosition entry should be added for it.
    """
    # The club member in the committee
    member = models.ForeignKey('Member')

    # The season in which the club member was on the committee
    season = models.ForeignKey('competitions.Season')

    # The committee position
    position = models.ForeignKey('CommitteePosition')

    objects = PassThroughManager.for_queryset_class(CommitteeMembershipQuerySet)()

    class Meta:
        """ Meta-info for the CommitteeMembership model."""
        app_label = 'members'
        ordering = ['member', 'position', 'season']
        # Only one person can hold a particular position in a particular season
        unique_together = ('position', 'season')

    def __unicode__(self):
        return unicode("{} - {} ({})".format(self.member, self.position, self.season))

cshcsite/members/models/member.py
""" The Member model represents a club member - specifically someone who
    participates in matches or holds a committee position.

    Members may be linked to website Users (CshcUser) - this enables the
    user's profile page to display stats and details pertaining to their
    member model. In particular, it lets the user upload a profile picture
    for their member model.
"""

import os
from django.conf import settings
from django.db import models
from django_resized import ResizedImageField
from model_utils import Choices
from core.models import make_unique_filename


def get_file_name(instance, filename):
    """ Returns a unique filename for profile pictures."""
    filename = make_unique_filename(filename)
    return os.path.join('uploads/profile_pics', filename)


class MemberManager(models.Manager):

    def get_query_set(self):
        return super(MemberManager, self).get_query_set().extra(select={"pref_name":"COALESCE(NULLIF(known_as, ''), first_name)"}, order_by=["pref_name", "last_name"])


class Member(models.Model):
    """ Represents a member of Cambridge South Hockey Club. Alternatively this can
        be thought of as a 'Player' model.

        User accounts will be associated with a member instance wherever possible.
    """

    user = models.OneToOneField(settings.AUTH_USER_MODEL, null=True, blank=True,
                                on_delete=models.SET_NULL)

    # Members first name (required)
    first_name = models.CharField(max_length=100, default=None)

    # The first name by which the member is typically known (optional)
    known_as = models.CharField(max_length=100, default=None, null=True, blank=True)

    # Members surname (required)
    last_name = models.CharField(max_length=100, default=None)

    # Members can be either male or female. That's all. Deal with it!
    GENDER = Choices('Male', 'Female')

    # Each member has a preferred position (or unknown)
    POSITION = Choices((0, 'GK', 'Goalkeeper'),
                       (1, 'GK_Def', 'Goalkeeper/Defender'),
                       (2, 'GK_Mid', 'Goalkeeper/Midfielder'),
                       (3, 'GK_Fwd', 'Goalkeeper/Forward'),
                       (4, 'Def', 'Defender'),
                       (5, 'Def_Mid', 'Defender/Midfielder'),
                       (6, 'Mid', 'Midfielder'),
                       (7, 'Mid_Fwd', 'Midfielder/Forward'),
                       (8, 'Fwd', 'Forward'),
                       (9, 'Other', 'Not known'))

    # An optional profile picture of the member
    profile_pic = ResizedImageField("Profile picture", max_width=400, max_height=400,
                                    upload_to=get_file_name, null=True, blank=True)

    # The member's gender
    gender = models.CharField("Gender", max_length=6, choices=GENDER, default=GENDER.Male)

    # The member's preferred playing position. Defaults to 'not known'.
    pref_position = models.IntegerField("Preferred position", choices=POSITION,
                                        default=POSITION.Other)

    # Indicates whether this member is a current member of the club. Useful for filtering etc.
    is_current = models.BooleanField(default=True)

    # Players shirt number
    shirt_number = models.CharField(max_length=4, blank=True)

    objects = MemberManager()

    class Meta:
        """ Meta-info for the Member model."""
        app_label = 'members'
        ordering = ['first_name', 'last_name']

    def __unicode__(self):
        return unicode(self.full_name())

    @models.permalink
    def get_absolute_url(self):
        """ Returns the url for this member instance."""
        return ('member_detail', [self.pk])

    def pref_first_name(self):
        """ Returns the member's preferred first name (known_as if set; otherwise first_name) """
        return self.known_as if self.known_as else self.first_name

    def full_name(self):
        """ Returns the member's full name."""
        return u"{} {}".format(self.pref_first_name(), self.last_name)

    def first_name_and_initial(self):
        """ Returns the shortened name display for this member."""
        return u"{} {}".format(self.pref_first_name(), self.last_name[0])

cshcsite/members/models/squad_membership.py
""" The SquadMembership model nominally associates a member with a
    particular CSHC team. This is currently just used for displaying
    the team link on a member's profile page. Additionally it can be
    used to filter member lists a bit more intelligently - for example
    when selecting the players who played in a match.
"""

from django.db import models
from django.db.models.query import QuerySet
from django.core.exceptions import ValidationError
from model_utils.managers import PassThroughManager
from competitions.models import Season
from teams.models import ClubTeam


def validate_squad(team_id):
    """ Utility validation method to make sure members aren't assigned to
        the Mixed or Indoor or Vets squads.
    """
    try:
        team = ClubTeam.objects.get(pk=team_id)
        if team.short_name.lower() in ('mixed', 'indoor', 'mv'):
            raise ValidationError("Squad assignments must be to one of the Men's or Ladies teams")
    except ClubTeam.DoesNotExist:
        raise ValidationError("Team not found")


class SquadMembershipQuerySet(QuerySet):
    """ Queries that relate to Squad Membership"""

    def by_member(self, member):
        """Returns only squad membership for the specified member"""
        return self.filter(member=member)

    def by_team(self, team):
        """Returns only squad membership for the specified team"""
        return self.filter(team=team)

    def by_season(self, season):
        """Returns only squad membership for the specified season"""
        return self.filter(season=season)

    def current(self):
        """ Returns only current squad membership, if any."""
        return self.filter(season=Season.current())


class SquadMembership(models.Model):
    """ A player is nominally assigned to a squad each season. This models
        maintains info on squad membership over the years.
    """
    # The club member in a squad
    member = models.ForeignKey('Member')

    # The team (squad) which the club member was a part of
    team = models.ForeignKey('teams.ClubTeam', validators=[validate_squad])

    # The season in which the club member was in the team
    season = models.ForeignKey('competitions.Season')

    objects = PassThroughManager.for_queryset_class(SquadMembershipQuerySet)()

    class Meta:
        """ Meta-info for the SquadMembership model."""
        app_label = 'members'
        ordering = ['member', 'season']
        # A member can only be in one squad in a particular season
        unique_together = ('member', 'team', 'season')

    def __unicode__(self):
        return unicode("{} - {} ({})".format(self.member, self.team, self.season))

cshcsite/members/forms.py
""" Custom forms for the Member models.
"""

from django import forms
from members.models import Member


class ProfileEditForm(forms.ModelForm):
    """Form used to edit your own profile"""

    class Meta:
        """ Meta-info for the form."""
        model = Member
        # our_notes is only to be used by staff/admin
        exclude = ('first_name', 'last_name', 'gender', 'is_current', 'user', 'shirt_number')

cshcsite/templates/members/_match_stats.html
{% load core_tags %}

{% url 'match_list' as match_list_url %}

{% if seasons %}

    <table class="table table-striped table-hover table-condensed table-center-align">
        <thead>
            <tr>
                <th rowspan="2" class="left-align">Season</th>
                {% if flavour = 'mobile' %}
                <th colspan="3">All matches</th>
                {% else %}
                <th colspan="3">League</th>
                <th colspan="3">Cup</th>
                <th colspan="3">Friendly</th>
                {% endif %}
                <th colspan="2">Awards</th></tr>
            <tr>
                {% if flavour = 'mobile' %}
                <th><abbr title="Appearances">Apps</abbr></th>
                <th><abbr title="Goals">Gls</abbr></th>
                <th><abbr title="Clean Sheets">CS</abbr></th>
                {% else %}
                <th><abbr title="Appearances">Apps</abbr></th>
                <th><abbr title="Goals">Gls</abbr></th>
                <th><abbr title="Clean Sheets">CS</abbr></th>
                <th><abbr title="Appearances">Apps</abbr></th>
                <th><abbr title="Goals">Gls</abbr></th>
                <th><abbr title="Clean Sheets">CS</abbr></th>
                <th><abbr title="Appearances">Apps</abbr></th>
                <th><abbr title="Goals">Gls</abbr></th>
                <th><abbr title="Clean Sheets">CS</abbr></th>
                {% endif %}
                <th><i class="icon-star"></i><abbr title="Man of the Match">MOM</abbr></th>
                <th><i class="icon-lemon"></i><abbr title="Lemon of the Match">LOM</abbr></th>
            </tr>
        </thead>
        <tbody>
            {% for season in seasons %}
            <tr{% if season.is_total %} class="info total"{% endif %}>
                <td class="left-align">
                    {% if season.is_total %}
                        Total
                    {% else %}
                        <a href="{{ match_list_url }}?players={{ member.id }}&season={{ season.season.id }}" title="List matches in {{ season.season }} for {{ member.pref_first_name }}">
                            {{ season.season }}
                        </a>
                    {% endif %}
                </td>
                {% if flavour = 'mobile' %}
                <td>{{ season.matches.all.appearances|default:"" }}</td>
                <td>{{ season.matches.all.goals|default:"" }}</td>
                <td>{{ season.matches.all.clean_sheets|default:"" }}</td>
                {% else %}
                <td>
                    {% if season.is_total %}
                        <a href="{{ match_list_url }}?players={{ member.id }}&fixture_type=League" title="List all league matches for {{ member.pref_first_name }}">
                            {{ season.matches.league.appearances|default:"" }}
                        </a>
                    {% else %}
                        <a href="{{ match_list_url }}?players={{ member.id }}&season={{ season.season.id }}&fixture_type=League" title="List league matches in {{ season.season }} for {{ member.pref_first_name }}">
                            {{ season.matches.league.appearances|default:"" }}
                        </a>
                    {% endif %}
                </td>
                <td>{{ season.matches.league.goals|default:"" }}</td>
                <td>{{ season.matches.league.clean_sheets|default:"" }}</td>
                <td>
                    {% if season.is_total %}
                        <a href="{{ match_list_url }}?players={{ member.id }}&fixture_type=Cup" title="List all cup matches for {{ member.pref_first_name }}">
                            {{ season.matches.cup.appearances|default:"" }}
                        </a>
                    {% else %}
                        <a href="{{ match_list_url }}?players={{ member.id }}&season={{ season.season.id }}&fixture_type=Cup" title="List cup matches in {{ season.season }} for {{ member.pref_first_name }}">
                            {{ season.matches.cup.appearances|default:"" }}
                        </a>
                    {% endif %}
                </td>
                <td>{{ season.matches.cup.goals|default:"" }}</td>
                <td>{{ season.matches.cup.clean_sheets|default:"" }}</td>
                <td>
                    {% if season.is_total %}
                        <a href="{{ match_list_url }}?players={{ member.id }}&fixture_type=Friendly" title="List all friendly matches for {{ member.pref_first_name }}">
                            {{ season.matches.friendly.appearances|default:"" }}
                        </a>
                    {% else %}
                        <a href="{{ match_list_url }}?players={{ member.id }}&season={{ season.season.id }}&fixture_type=Friendly" title="List friendly matches in {{ season.season }} for {{ member.pref_first_name }}">
                            {{ season.matches.friendly.appearances|default:"" }}
                        </a>
                    {% endif %}
                </td>
                <td>{{ season.matches.friendly.goals|default:"" }}</td>
                <td>{{ season.matches.friendly.clean_sheets|default:"" }}</td>
                {% endif %}
                <td>{{ season.matches.mom|default:"" }}</td>
                <td>{{ season.matches.lom|default:"" }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% else %}
    <p class="lead muted">Sorry - no stats available</p>
{% endif %}

cshcsite/templates/members/_member_details.html
{% url 'user_profile' as user_profile %}
{% url 'about_committee' as committee_url %}

<div class="row">
    <div class="span8">
        {% if squad %}
            <h3><i class="icon-group"></i>Squad <span class="smaller muted">({{ squad.season }})</span>: <a class="smaller" href="{{ squad.team.get_absolute_url }}" title="Team details...">{{ squad.team.long_name }}</a></h3>
        {% endif %}

        <div id="stats-wrapper">
        <h3><i class="icon-table icon-large"></i>Player Stats</h3>
            {% include 'core/_loading_placeholder.html' with placeholder_id="stats" placeholder_text="Loading member stats..." %}
        </div>
    </div>

    <div class="span4">
        {% if member.profile_pic %}
            <img id="profile-pic" class="profile-pic-large" src="{{ member.profile_pic.url }}"/>
        {% else %}
            <img id="profile-pic" class="profile-pic-large" src="{{ STATIC_URL }}media/profile_pics/default.jpg"/>
        {% endif %}
        {% if member.user == request.user and is_profile %}
        <div class="box side-box">
            {% url 'auth_password_change' as password_change %}
            <div class="accordion" id="edit-profile-accordion">
                <div class="accordion-group">
                    <div class="accordion-heading">
                      <a class="accordion-toggle" data-toggle="collapse" data-parent="#edit-profile-accordion" href="#collapseOne">
                        Edit your profile
                      </a>
                    </div>
                    <div id="collapseOne" class="accordion-body collapse">
                      <div class="accordion-inner">
                        <form enctype="multipart/form-data" action="{{ user_profile }}" method="post">{% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" value="Save" />
                        </form>
                        <p><a href="{{ password_change }}">Change your password...</a></p>
                      </div>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>

<div class="row">
{% if recent_match_reports %}
<div class="span8">
    <h3><i class="icon-file-alt icon-large"></i>Match reports by {{ member }}</h3>
    <table class="table table-condensed">
        <tbody>
            {% for match in recent_match_reports %}
                <tr><td>{{ match.date|date:"d-M-y" }}</td><td><a href="{{ match.get_absolute_url }}">{{ match.report_title }}</a></td></tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}

{% if recent_match_awards %}
<div class="span4">
    <h3><i class="icon-star icon-large"></i>Latest match awards</h3>
    <table class="table table-condensed">
        <tbody>
            {% for award in recent_match_awards %}
                <tr><td>{{ award.match.date|date:"d-M-y" }}</td><td><a href="{{ award.match.get_absolute_url }}" title="Match details">{{ award.award.name }}</a></td></tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}

{% if recent_end_of_season_awards %}
<div class="span4">
    <h3><i class="icon-trophy icon-large"></i>End of Season Awards</h3>
    <table class="table table-condensed">
        <tbody>
            {% for award in recent_end_of_season_awards %}
                <tr><td>{{ award.season }}</td><td>{{ award.award.name }}</td></tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %}

{% comment %} 
{% if committee_positions %}
<div class="span4">
    <h3><i class="icon-group icon-large"></i>Committee Positions</h3>
    <table class="table table-condensed">
        <tbody>
            {% for membership in committee_positions %}
                <tr>
                    <td>
                        <a href="{{ committee_url }}{{ membership.season }}" title="View {{ membership.season }} committee">
                        {{ membership.season }}
                        </a>
                    </td>
                    <td>{{ membership.position.name }}</td></tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endif %} {% endcomment %}

</div>

cshcsite/templates/members/_member_details_js.html
{% url 'member_stats_ajax' member.pk as member_stats %}
<script>
    $(function () {
        ajax_load('{{ member_stats }}', 'stats');
    });
</script>

cshcsite/templates/members/_member_stats.html
<div class="tabbable"> 
    <ul class="nav nav-tabs">
        <li class="active"><a href="#tabMatches" data-toggle="tab">Matches, Goals &amp; Awards</a></li>
        <li><a href="#tabTeamRep" data-toggle="tab">Team Representations</a></li>
        <li><a href="#tabSuccessRec" data-toggle="tab">Success Record</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="tabMatches">
            {% include 'members/_match_stats.html' %}
        </div>
        <div class="tab-pane" id="tabTeamRep">
            {% include 'members/_team_stats.html' %}
        </div>
        <div class="tab-pane" id="tabSuccessRec">
            {% include 'members/_success_stats.html' %}
        </div>
    </div>
</div>

cshcsite/templates/members/_profile_pic_thumbnail.html
{% comment %}
Reusable snippet that displays a thumbnail of the member's profile picture if they have one, or
the default member avatar if not.

Expected context:
'member' - the member model instance
{% endcomment %}

{% load thumbnail %}
{% thumbnail member.profile_pic "50x50" crop="center" as im %}
    <img class="profile-pic" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
{% empty %}
	{#<img class="profile-pic" src="{{ STATIC_URL }}media/profile_pics/default.jpg" width="50" height="50">#}
    <span class="shirt-number {{ member.gender|lower }}">{{ member.shirt_number|default:"" }}</span>
{% endthumbnail %}

{# TEMP #}
{#<img src="{{ STATIC_URL }}media/profile_pics/default.jpg" width="50" height="50">#}

cshcsite/templates/members/_team_rep.html
{% if season.is_total %}
    <a href="{{ match_list_url }}?players={{ member.id }}&our_team={{ appearances.id }}" title="List all matches {{ member.pref_first_name }} played for the {{ team_name }} team">
        {{ appearances.count|default:"" }}
    </a>
{% else %}
    <a href="{{ match_list_url }}?players={{ member.id }}&season={{ season.season.id }}&our_team={{ appearances.id }}" title="List matches {{ member.pref_first_name }} played for the {{ team_name }} team in {{ season.season }}">
        {{ appearances.count|default:"" }}
    </a>
{% endif %}

cshcsite/templates/members/member_detail.html
{% extends "base.html" %}
{% load core_tags %}

{% comment %}
Formatted display of the details of a particular member.
- Used by member_details_view
Currently just lists the values that will be needed by this template - no UI design here yet!
{% endcomment %}

{% block title %}{{ block.super }} | {{ member }}{% endblock %}

{% block body_id %}member-detail{% endblock body_id %}

{% block content %}

{% url 'member_list' as member_list_url %}

<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="{{ member_list_url }}">Members</a> <span class="divider">/</span></li>
  <li class="active">{{member }}</li>
</ul>

<div class="page-header">
  <h1>{{ member }} {% if member.pref_position != 9 %}<small>{{ member.get_pref_position_display|capfirst }} </small>{% endif %}{% if member.is_current %}<span class="label label-success">Current</span>{% endif %}
<span id="shirt-number" class="no-mobile pull-right {{ member.gender|lower }}" {% if member.shirt_number %}title="Shirt number: {{ member.shirt_number }}"{% endif %}>{{ member.shirt_number|default:"" }}</span>
  </h1>
</div>

{% include 'members/_member_details.html' %}

{% instance_admin_links member %}

{% endblock %}

{% block body_js %}
{{ block.super }}
{% include 'members/_member_details_js.html' %}
{% endblock body_js %}

cshcsite/templates/members/member_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% load core_tags %}
{% load i18n %}
{% load pagination_tags %}
{% load sorter_tags %}

{% comment %}
Filter-able, sortable, paginated display of members.
{% endcomment %}

{% block title %}{{ block.super }} | Club members{% endblock %}

{% block body_id %}member-list{% endblock body_id %}

{% block content %}

<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Members</li>
</ul>

<div class="page-header">
    <h1>Club members</h1>
</div>

    {% sort filter.qs as sorted_list %}
    {% autopaginate sorted_list 40 as sorted_filter_list %}

    {% paginate %}

    {% if sorted_filter_list %}
        <table id="members" class="table table-hover table-middle-align">
            <thead>
                <tr>
                    <th class="priority3"></th>
                    <th>{% sortlink by "first_name" "-first_name" %}First Name{% endsortlink %}</th>
                    <th>{% sortlink by "last_name" "-last_name" %}Last Name{% endsortlink %}</th>
                    <th class="priority3">{% sortlink by "gender" "-gender" %}M/F{% endsortlink %}</th>
                    <th>{% sortlink by "pref_position" "-pref_position" %}Position{% endsortlink %}</th>
                    <th class="center-align">{% sortlink by "shirt_number" "-shirt_number" %}Shirt #{% endsortlink %}</th>
                    <th class="center-align">Appearances</th>
                    <th class="center-align">Goals</th>
                </tr>
            </thead>
            <tbody>
            {% for member in sorted_filter_list %}
            {% with member_url=member.get_absolute_url %}
                <tr class="member-row" onclick="window.location='{{ member_url }}';" title="{{ member.full_name }} - member details">
                    <td class="priority3"><a href="{{ member_url }}" title="Member details">{% include 'members/_profile_pic_thumbnail.html' %}</a></td>
                    <td>{{ member.first_name }} {% if member.known_as %} ({{ member.known_as }}){% endif %}</td>
                    <td>{{ member.last_name }}</td>
                    <td class="priority3">{{ member.get_gender_display }}</td>
                    <td>{{ member.get_pref_position_display }}</td>
                    <td class="center-align">{{ member.shirt_number|default:"" }}</td>
                    <td class="center-align">{{ member.num_appearances|default:"" }}</td>
                    <td class="center-align">{{ member.goals|default:"" }}</td>
                </tr>
            {% endwith %}
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p class="lead muted">No members found!</p>
    {% endif %}

    {% paginate %}

    {% model_admin_links 'members' 'member' %}

{% endblock content %}