cshcsite/teams/urls.py
""" URL routing for views relating to teams.
"""

from django.conf.urls import patterns, url
from teams import views, feeds


urlpatterns = patterns('',

    # E.g. '/teams/'                            - List of all CSHC teams
    url(r'^/?$',
        views.ClubTeamListView.as_view(),
        name="clubteam_list"
    ),

    # E.g. '/teams/playing-record/'             - The playing records through the seasons of each team
    url(r'^playing-record/$',
        views.PlayingRecordView.as_view(),
        name="playing_record"
    ),

    # E.g. '/teams/playing-record/ajax/'        - AJAX-only: Updates and refreshes the playing records of each team
    url(r'^playing-record/ajax/$',
        views.PlayingRecordUpdateView.as_view(),
        name="playing_record_update"
    ),

    # E.g. '/teams/southerners/'                - Statistics table comparing the performance of CSHC teams this season
    url(r'^southerners/$',
        views.SouthernersSeasonView.as_view(),
        name="southerners_league"
    ),

    # E.g. '/teams/southerners/2011-2012/'      - Statistics table comparing the performance of CSHC teams in a previous season
    url(r'^southerners/(?P<season_slug>[-\w]+)/$',
        views.SouthernersSeasonView.as_view(),
        name="southerners_league_season"
    ),

    # E.g. '/teams/southerners/2011-2012/ajax/' - AJAX-only: Updates and refreshes the Southerners statistics
    url(r'^southerners/(?P<season_slug>[-\w]+)/ajax/$',
        views.SouthernersSeasonUpdateView.as_view(),
        name="southerners_league_season_update"
    ),

    # E.g. '/teams/m1/'                         - Details of a particular CSHC team (including the team's playing record) for the current season
    url(r'^(?P<slug>[-\w]+)/$',
        views.ClubTeamDetailView.as_view(),
        name="clubteam_detail"
    ),

    # E.g. '/teams/m1/2011-2012/'               - Details of a particular CSHC team (including the team's playing record) for a previous season
    url(r'^(?P<slug>[-\w]+)/(?P<season_slug>[-\w]+)/$',
        views.ClubTeamDetailView.as_view(),
        name="clubteam_season_detail"
    ),

    # E.g. /teams/m1.ics'                       - Calendar feed of a particular team's matches
    url(r'^(?P<slug>[-\w]+).ics$',
        feeds.ClubTeamMatchICalFeed(),
        name="clubteam_ical_feed"
    ),

    # E.g. /teams/m1.rss'                       - RSS feed of a particular team's match reports
    url(r'^(?P<slug>[-\w]+).rss$',
        feeds.RssClubTeamMatchReportsFeed(),
        name="clubteam_match_rss_feed"
    ),

    # E.g. '/teams/participation/23/ajax/'      - AJAX-only: Updates and refreshes the playing record stats for a particular team in a particular season
    url(r'^participation/(?P<participation_id>\d+)/ajax/$',
        views.ParticipationUpdateView.as_view(),
        name="participation_update"
    ),

    # E.g. '/teams/m1/stats/3/ajax/'             - AJAX-only: Retrieves fixture list, league table and squad membership for a particular team/season
    url(r'^(?P<slug>[-\w]+)/stats/(?P<season_pk>\d+)/ajax/$',
        views.ClubTeamStatsView.as_view(),
        name='clubteam_stats_ajax'),

    # E.g. '/teams/m1/stats/3/ajax/scrape/'      - AJAX-only: Scrapes the external league table website and updates and refreshes the league table for a particular team/season
    url(r'^(?P<slug>[-\w]+)/stats/(?P<season_pk>\d+)/ajax/scrape/$',
        views.ScrapeLeagueTableView.as_view(),
        name='refresh_league_table'),

)

cshcsite/competitions/models/league.py
""" The League model represents a single hockey league,
    which can be made up of multiple divisions.
"""

from django.db import models


class League(models.Model):
    """Represents a hockey league"""

    # The (unique) name of the league
    name = models.CharField("League Name", max_length=255, unique=True, default=None)

    # The (external) league website - optional
    url = models.URLField("League Website", blank=True,
                          help_text="The club's website (if it has one)")

    class Meta:
        """ Meta-info for the League model."""
        app_label = 'competitions'
        ordering = ['name']

    def __unicode__(self):
        return unicode(self.name)

cshcsite/opposition/models/team.py
""" The Team model represents an opposition team within a club.

    Teams are simply identified by a name but are also marked as
    Mens/Ladies/Mixed.
"""

from django.db import models
from django.template.defaultfilters import slugify
from core.models import TeamGender
from opposition.models.club import Club


class TeamManager(models.Manager):
    """Model manager for the Team model"""

    def mens(self):
        """Returns only men's teams"""
        return self.get_query_set().filter(gender=TeamGender.Mens)

    def ladies(self):
        """Returns only ladies teams"""
        return self.get_query_set().filter(gender=TeamGender.Ladies)

    def mixed(self):
        """Returns only mixed teams"""
        return self.get_query_set().filter(gender=TeamGender.Mixed)


class Team(models.Model):
    """Represents an opposition team"""

    # The club this team is a part of
    club = models.ForeignKey(Club, related_name="teams")

    # Full name of the team
    name = models.CharField("Team name", max_length=100, unique=True)

    # Abbreviated name of the team
    short_name = models.CharField("Abbreviated name", max_length=100)

    # Mens/ladies/mixed team
    gender = models.CharField("Team gender (mens/ladies)", max_length=6, choices=TeamGender)

    # Auto-generated slug
    slug = models.SlugField("Slug")

    objects = TeamManager()

    class Meta:
        """ Meta-info for the Team model."""
        app_label = 'opposition'
        ordering = ['club', 'name']

    def clean(self):
        self.slug = slugify(self.name)

    def __unicode__(self):
        return unicode(self.name)

    def genderless_name(self):
        """ Utility method to get the team name without 'Mens' or 'Ladies' in it."""
        return self.name.replace(" Ladies", "").replace(" Mens", "")

cshcsite/teams/models/participation.py
""" The ClubTeamSeasonParticipation model is used to track
    details about a particular team for a particular season.

    There should be one instance per team/season combination.
"""

import os
from django.db import models
from django.db.models.query import QuerySet
from django.core.exceptions import ValidationError
from django_resized import ResizedImageField
from model_utils import Choices
from model_utils.managers import PassThroughManager
from core.utils import ordinal
from core.models import not_none_or_empty, make_unique_filename
from competitions.models import Season, Division, Cup
from teams.models.club_team import ClubTeam

# The directory where uploaded team photos should be stored (within MEDIA_URL)
TEAM_PHOTO_DIR = 'uploads/team_photos'

def get_file_name(instance, filename):
    """ Returns a unique filename for uploaded team photos. """
    filename = make_unique_filename(filename)
    return os.path.join(TEAM_PHOTO_DIR, filename)


class ClubTeamSeasonParticipationQuerySet(QuerySet):
    """ Queries relating to the ClubTeamSeasonParticipation model"""

    def current(self):
        """ Returns just the participations for the current season"""
        return self.filter(season=Season.current())

    def by_season(self, season):
        """ Returns just the participations for the specified season"""
        return self.filter(season=season)

    def by_team(self, team):
        """ Returns just the participations for the specified team"""
        return self.filter(team=team)


class ClubTeamSeasonParticipation(models.Model):
    """ Represents the participation of a Cambridge South team in a particular season.

        Includes division and cup participation.
    """

    DIVISION_RESULT = Choices('Promoted', 'Relegated', 'Champions')

    team = models.ForeignKey(ClubTeam)
    """The Cambridge South team participating in the division"""

    season = models.ForeignKey(Season)
    """The season in which the team participated in the division"""

    # Division ################################################################

    division = models.ForeignKey(Division, null=True, blank=True)
    """The division in which the team participated in, if any."""

    team_photo = ResizedImageField("Team photo", max_width=900, max_height=600,
                                   upload_to=get_file_name, null=True, blank=True)
    """A team photo (if available) from this sesason"""

    team_photo_caption = models.TextField(blank=True)
    """Caption for the team photo. Could include a list of who's who."""

    final_pos = models.PositiveSmallIntegerField("Final position", null=True,
                                                 blank=True, default=None,
                                                 help_text="Once the season is complete, enter the final league position here")
    """The final league position of the team"""

    division_result = models.CharField(max_length=20, choices=DIVISION_RESULT,
                                       null=True, blank=True, default=None,
                                       help_text="Set to one of the options if the team was promoted or relegated this season.")
    """Indicates if the team was promoted or relegated this season"""

    # The (external) URL of the division leauge table
    division_tables_url = models.URLField("League table website", blank=True)

    # The (external) URL of the division fixtures list
    division_fixtures_url = models.URLField("Fixtures website", blank=True)

    # Cup #####################################################################

    cup = models.ForeignKey(Cup, null=True, blank=True)
    """The cup the team participated in, if any."""

    cup_result = models.CharField("Cup result", max_length=100, null=True, blank=True, default=None,
                                  help_text="Where did the team get to in the cup? (Enter once cup participation is complete)")
    """How the team got on in the cup"""

    blurb = models.TextField(blank=True)
    """Some optional comments about the team this season."""

    # Statistics (updated with a script on a regular basis for the current season)
    # Note - these fields will not show up on the admin interface

    friendly_played = models.PositiveSmallIntegerField("Friendly games played", default=0)
    friendly_won = models.PositiveSmallIntegerField("Friendly games won", default=0)
    friendly_drawn = models.PositiveSmallIntegerField("Friendly games drawn", default=0)
    friendly_lost = models.PositiveSmallIntegerField("Friendly games lost", default=0)
    friendly_goals_for = models.PositiveSmallIntegerField("Friendly goals for", default=0)
    friendly_goals_against = models.PositiveSmallIntegerField("Friendly goals against", default=0)

    cup_played = models.PositiveSmallIntegerField("Cup games played", default=0)
    cup_won = models.PositiveSmallIntegerField("Cup games won", default=0)
    cup_drawn = models.PositiveSmallIntegerField("Cup games drawn", default=0)
    cup_lost = models.PositiveSmallIntegerField("Cup games lost", default=0)
    cup_goals_for = models.PositiveSmallIntegerField("Cup goals for", default=0)
    cup_goals_against = models.PositiveSmallIntegerField("Cup goals against", default=0)

    league_played = models.PositiveSmallIntegerField("League games played", default=0)
    league_won = models.PositiveSmallIntegerField("League games won", default=0)
    league_drawn = models.PositiveSmallIntegerField("League games drawn", default=0)
    league_lost = models.PositiveSmallIntegerField("League games lost", default=0)
    league_goals_for = models.PositiveSmallIntegerField("League goals for", default=0)
    league_goals_against = models.PositiveSmallIntegerField("League goals against", default=0)

    objects = PassThroughManager.for_queryset_class(ClubTeamSeasonParticipationQuerySet)()

    class Meta:
        """ Meta-info for the ClubTeamSeasonParticipation model."""
        app_label = 'teams'
        # A team can only participate once per season!
        unique_together = ('team', 'season')

    def __unicode__(self):
        return unicode("{} - {}".format(self.team, self.season))

    def clean(self):
        # Sanity checks
        if not self.division and not_none_or_empty(self.division_result):
            raise ValidationError("Division result cannot be set if no division is selected.")

        if not self.division and self.final_pos is not None:
            raise ValidationError("Final position cannot be set if no division is selected.")

        if not self.cup and not_none_or_empty(self.cup_result):
            raise ValidationError("Cup result cannot be set if no cup is selected.")

        # Make sure the division gender matches the team gender!
        if self.division is not None and (self.team.gender != self.division.gender):
            raise ValidationError("{} is a {} team but {} is a {} division", self.team, self.team.get_gender_display(), self.division, self.division.get_gender_display());

        # Make sure the cup gender matches the team gender!
        if self.cup is not None and (self.team.gender != self.cup.gender):
            raise ValidationError("{} is a {} team but {} is a {} cup", self.team, self.team.get_gender_display(), self.cup, self.cup.get_gender_display());

    def total_played(self):
        """ Returns the total number of matches played. """
        return self.friendly_played + self.cup_played + self.league_played

    def total_won(self):
        """ Returns the total number of matches won. """
        return self.friendly_won + self.cup_won + self.league_won

    def total_drawn(self):
        """ Returns the total number of matches drawn. """
        return self.friendly_drawn + self.cup_drawn + self.league_drawn

    def total_lost(self):
        """ Returns the total number of matches lost. """
        return self.friendly_lost + self.cup_lost + self.league_lost

    def total_goals_for(self):
        """ Returns the total number of goals scored. """
        return self.friendly_goals_for + self.cup_goals_for + self.league_goals_for

    def total_goals_against(self):
        """ Returns the total number of goals conceded. """
        return self.friendly_goals_against + self.cup_goals_against + self.league_goals_against

    def friendly_goals_per_game(self):
        """ Returns the average number of goals scored per game in friendly matches. """
        if self.friendly_played == 0:
            return 0.0

        return float(self.friendly_goals_for) / float(self.friendly_played)

    def cup_goals_per_game(self):
        """ Returns the average number of goals scored per game in cup matches. """
        if self.cup_played == 0:
            return 0.0

        return float(self.cup_goals_for) / float(self.cup_played)

    def league_goals_per_game(self):
        """ Returns the average number of goals scored per game in league matches. """
        if self.league_played == 0:
            return 0.0

        return float(self.league_goals_for) / float(self.league_played)

    def total_goals_per_game(self):
        """ Returns the average number of goals scored per game in all matches. """
        if self.total_played() == 0:
            return 0.0

        return float(self.total_goals_for()) / float(self.total_played())

    def avg_goals_for(self):
        """ Returns the average number of goals scored per game in matches played by
            this team in this season.
        """
        if self.total_played() == 0:
            return 0.0

        return float(self.total_goals_for()) / float(self.total_played())

    def avg_goals_against(self):
        """ Returns the average number of goals scored per game by the opposition in
            matches played by this team in this season.
        """
        if self.total_played() == 0:
            return 0.0

        return float(self.total_goals_against()) / float(self.total_played())

    def reset(self):

cshcsite/teams/forms.py
""" Custom forms for the Teams models
"""

from django import forms
from redactor.widgets import RedactorEditor
from teams.models import ClubTeamSeasonParticipation, TEAM_PHOTO_DIR


class ClubTeamSeasonParticipationForm(forms.ModelForm):
    """ A form for entering Club Team Season Participation details.
        A Redactor widget is specified for editing the blurb and team_photo_caption fields.
    """
    class Meta:
        """ Meta-info for the form. """
        model = ClubTeamSeasonParticipation
        widgets = {
            'blurb': RedactorEditor(upload_to=TEAM_PHOTO_DIR,
                                    redactor_options={'minHeight': 150}),
            'team_photo_caption': RedactorEditor(upload_to=TEAM_PHOTO_DIR,
                                                 redactor_options={'minHeight': 150}),
        }

cshcsite/templates/teams/_clubteam_stats.html
<div class="tabbable"> 
  <ul class="nav nav-tabs">
    <li class="active"><a href="#tabFixRes" data-toggle="tab">Fixtures/Results</a></li>
    {% if division %}<li><a href="#tabLeagueTable" data-toggle="tab">League Table</a></li>{% endif %}
    <li><a href="#tabSquad" data-toggle="tab">Squad Roster</a></li>
  </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="tabFixRes">
      {% include 'matches/_fixture_list.html' %}
    </div>
    {% if division %}
    <div class="tab-pane" id="tabLeagueTable">
      {% include 'teams/_league_table.html' %}
    </div>
    {% endif %}
    <div class="tab-pane" id="tabSquad">
      {% include 'teams/_squad_list.html' %}
    </div>
  </div>
</div>

cshcsite/templates/teams/_league_table.html
<h4>{{ division }}&nbsp;&nbsp; <small>{{ season }}</small></h4>
{% if div_data %}
    <table class="table table-striped table-hover table-condensed">
        <thead>
            <tr><th>Team</th>
                <th><abbr title="Played">P</abbr></th>
                <th><abbr title="Won">W</th>
                <th><abbr title="Drawn">D</th>
                <th><abbr title="Lost">L</th>
                <th><abbr title="Goals For">GF</th>
                <th><abbr title="Goals Against">GA</th>
                <th><abbr title="Goal Difference">GD</th>
                <th><abbr title="Points">Pts</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for t in div_data %}
            <tr {% if t.team_name == clubteam.genderless_abbr_name %}class="success"{% endif %} >
                <td><a href="{% if t.our_team %}{{ t.our_team.get_absolute_url }}{% else %}{{ t.opp_team.club.get_absolute_url }}{% endif %}">{{ t.team_name|capfirst }}</a></td>
                <td>{{ t.played }}</td>
                <td>{{ t.won }}</td>
                <td>{{ t.drawn }}</td>
                <td>{{ t.lost }}</td>
                <td>{{ t.goals_for }}</td>
                <td>{{ t.goals_against }}</td>
                <td>{{ t.goal_difference }}</td>
                <td>{{ t.points }}</td>
                <td>{{ t.notes }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% else %}
    <p class="lead muted">Sorry - league table not available</p>
{% endif %}
{% if user.is_staff and is_current_season %}
    <button id="refresh-btn" class="btn btn-primary" type="button" title="Refresh league table" ><i id="refresh-icon" class="icon icon-refresh"></i><span id="refresh-text">Refresh</span></button>
    {% url 'refresh_league_table' clubteam.slug season.pk as refresh_league_table %}

    <script>
        $("#refresh-btn").click( function() {
            $("#refresh-icon").addClass('icon-spin');
            $("#refresh-text").text('Refreshing...');
            $('#refresh-btn').attr("disabled", true);
            $.ajax({
                url: '{{ refresh_league_table }}', cache: false, success: function (result) {
                    $("#tabLeagueTable").html(result);
                    $("#refresh-icon").removeClass('icon-spin');
                    $("#refresh-text").text('Refresh');
                    $('#refresh-btn').attr("disabled", false);
                }
            });
        });
    </script>
{% endif %}

cshcsite/templates/teams/_participation_stats.html
<table class="table table-striped table-hover table-condensed table-center-align table-middle-align">
    <thead>
        <tr>
            <th></th>
            <th><abbr title="Played">P</abbr></th>
            <th><abbr title="Won">W</abbr></th>
            <th><abbr title="Drawn">D</abbr></th>
            <th><abbr title="Lost">L</abbr></th>
            <th><abbr title="Goals for">GF</abbr></th>
            <th><abbr title="Goals against">GA</abbr></th>
            <th><abbr title="Goals per game">GPG</abbr></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td class="left-align">Friendly</td>
            <td>{{ participation.friendly_played }}</td>
            <td>{{ participation.friendly_won }}</td>
            <td>{{ participation.friendly_drawn }}</td>
            <td>{{ participation.friendly_lost }}</td>
            <td>{{ participation.friendly_goals_for }}</td>
            <td>{{ participation.friendly_goals_against }}</td>
            <td>{{ participation.friendly_goals_per_game|floatformat:1 }}</td>
        </tr>
        <tr>
            <td class="left-align">Cup</td>
            <td>{{ participation.cup_played }}</td>
            <td>{{ participation.cup_won }}</td>
            <td>{{ participation.cup_drawn }}</td>
            <td>{{ participation.cup_lost }}</td>
            <td>{{ participation.cup_goals_for }}</td>
            <td>{{ participation.cup_goals_against }}</td>
            <td>{{ participation.cup_goals_per_game|floatformat:1 }}</td>
        </tr>
        <tr>
            <td class="left-align">League</td>
            <td>{{ participation.league_played }}</td>
            <td>{{ participation.league_won }}</td>
            <td>{{ participation.league_drawn }}</td>
            <td>{{ participation.league_lost }}</td>
            <td>{{ participation.league_goals_for }}</td>
            <td>{{ participation.league_goals_against }}</td>
            <td>{{ participation.league_goals_per_game|floatformat:1 }}</td>
        </tr>
        <tr class="info total">
            <td class="left-align">Total</td>
            <td>{{ participation.total_played }}</td>
            <td>{{ participation.total_won }}</td>
            <td>{{ participation.total_drawn }}</td>
            <td>{{ participation.total_lost }}</td>
            <td>{{ participation.total_goals_for }}</td>
            <td>{{ participation.total_goals_against }}</td>
            <td>{{ participation.total_goals_per_game|floatformat:1 }}</td>
        </tr>
    </tbody>
</table>

cshcsite/templates/teams/_southerners_league_table.html
<table class="table table-condensed table-hover table-center-align">
    <thead>
        <tr>
            <th class="priority2">Rank</th>
            <th>Team</th>
            <th><abbr title="Played">P</abbr></th>
            <th><abbr title="Won">W</abbr></th>
            <th><abbr title="Drawn">D</abbr></th>
            <th><abbr title="Lost">L</abbr></th>
            <th class="priority2"><abbr title="Goals For">GF</abbr></th>
            <th class="priority2"><abbr title="Goals Against">GA</abbr></th>
            <th class="priority2">Result Points</th>
            <th class="priority2">Bonus Points</th>
            <th>Total Points</th>
            <th>Avg Points/Game</th>
    </thead>
    <tbody>
        {% for team in team_list %}
        <tr>
            <td class="priority2">{{ team.rank }}</td>
            <td>{{ team.team }}</td>
            <td>{{ team.played }}</td>
            <td>{{ team.won }}</td>
            <td>{{ team.drawn }}</td>
            <td>{{ team.lost }}</td>
            <td class="priority2">{{ team.goals_for }}</td>
            <td class="priority2">{{ team.goals_against }}</td>
            <td class="priority2">{{ team.result_points }}</td>
            <td class="priority2">{{ team.bonus_points }}</td>
            <td>{{ team.total_points }}</td>
            <td>{{ team.avg_points_per_game|floatformat:1 }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

cshcsite/templates/teams/clubteam_detail.html
{% extends "base.html" %}
{% load core_tags %}
{% load humanize %}

{% comment %}
Formatted display of the details of a particular team.
- Used by clubteam_detail and clubteam_season_detail
Currently just lists the values that will be needed by this template - no UI design here yet!
{% endcomment %}


{% block title %}{{ block.super }} | {{ clubteam.long_name }}{% endblock %}

{% block body_id %}team-detail{% endblock body_id %}

{% block content %}
{% url 'clubteam_list' as clubteam_list_url %}
{% url 'clubteam_detail' clubteam.slug as base_team_url %}
{% url 'clubteam_ical_feed' clubteam.slug as clubteam_calendar %}
{% url 'clubteam_match_rss_feed' clubteam.slug as clubteam_rss %}

<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="{{ clubteam_list_url }}">Teams</a> <span class="divider">/</span></li>
  <li class="active">{{ clubteam.long_name }}</li>
</ul>

<div class="row">
    <div class="span7">
        <div class="page-header">
            <h1>{{ clubteam.long_name }} <small>{{ season }}</small>
            </h1>
        </div>
    </div>
    <div class="span5">
        <div class="pull-right">
            <h1><a class="no-mobile" href="{{ clubteam_calendar }}" target="_blank" title="{{ clubteam.long_name }} calendar"><i class="icon-calendar icon-small"></i></a>
                    <a href="{{ clubteam_rss }}" target="_blank" title="{{ clubteam.long_name }} match report RSS feed"><i class="icon-rss icon-small"></i></a>{% include 'core/_season_selector.html' with url_prefix=base_team_url %}</h1>
        </div>
    </div>
</div>

<div class="row">
    <div class="span6">
        {% if participation and participation.division %}
                <p class="lead">{{ participation.division }}
                {% if participation.final_pos %}
                    <strong>- finished {{ participation.final_pos|ordinal }}</strong>
                {% endif %}
                {% if participation.division_result %}
                    <strong> ({{ participation.get_division_result_display }})</strong>
                {% endif %}
                </p>
        {% endif %}
        {% if participation and participation.blurb %}
            <p>{{ participation.blurb|safe }}</p>
        {% else %}
            <p>{{ clubteam.blurb|safe }}</p>
        {% endif %}

        <table id="captains-table" class="table table-clean table-hcondensed">
        <tbody>
            <tr><td class="dt">Captain{% if captains|length > 1 %}s{% endif %}:</td>
            {% if captains %}
                <td>
                    {% for c in captains %}
                        <strong>{{ c.member|urlise_model }}</strong>
                        {% if not forloop.last %}<br/>{% endif %}
                    {% endfor %}
                </td>
            {% else %}
                <td><strong>(Unknown)</strong></td>
                <td>{% model_admin_links 'teams' 'teamcaptaincy' changelist=False %}</td>
            {% endif %}
            </tr>
            {% if vice_captains %}
            <tr><td class="dt">Vice-captain{% if vice_captains|length > 1 %}s{% endif %}:</td>
                <td>
                    {% for vc in vice_captains %}
                        <strong>{{ vc.member|urlise_model }}</strong>
                        {% if not forloop.last %}<br/>{% endif %}
                    {% endfor %}
                </td>
            </tr>
            {% endif %}
        </tbody>
        </table>
        <div class="row quick-links">
            {% if participation and participation.division_tables_url %}
                <a href="{{ participation.division_tables_url }}" target="_blank" title="{{ participation.division }} league tables"><button class="btn btn-success"><i class="icon-external-link"></i>League Table</button></a>
            {% else %}
                <button disabled class="btn" title="No league table available on the league website"><i class="icon-external-link"></i>League Table</button>
            {% endif %}
            {% if participation and participation.division_fixtures_url %}
                <a href="{{ participation.division_fixtures_url }}" target="_blank" title="{{ participation.division }} fixtures/results"><button class="btn btn-success"><i class="icon-external-link"></i>Fixtures/Results</button></a>
            {% else %}
                <button disabled class="btn" title="No fixtures/results available on the league website"><i class="icon-external-link"></i>Fixtures/Results</button>
            {% endif %}

            {% if participation %}
                {% instance_admin_links participation %}
            {% else %}
                {% model_admin_links 'teams' 'clubteamseasonparticipation' %}
            {% endif %}
        </div>
        <div id="participation-stats-table">
            {% include "teams/_participation_stats.html" %}
        </div>
        {% if user.is_staff %}
            <button id="refresh-btn" class="btn btn-primary" type="button" title="Refresh Team stats for {{ participation.season }}" ><i id="refresh-icon" class="icon icon-refresh"></i><span id="refresh-text">Refresh</span></button>
        {% endif %}
    </div>
    <div class="span6">
        <img src="{% if participation.team_photo %}{{ participation.team_photo.url }}{% else %}{{ STATIC_URL }}media/team_photos/placeholder.jpg{% endif %}" class="img-rounded pull-right team-photo"></img>
        <p class="caption">{{ participation.team_photo_caption }}</p>
    </div>
</div>

{% include 'core/_loading_placeholder.html' with placeholder_id="clubteam-info" placeholder_text="Loading team stats..." %}

{% instance_admin_links clubteam %}

{% endblock %}

{% block body_js %}
{{ block.super }}

{% url 'clubteam_stats_ajax' clubteam.slug season.pk as clubteam_stats %}
{% url 'participation_update' participation.pk as refresh_participation_stats %}

<script>
    $(function () {
        ajax_load('{{ clubteam_stats }}', 'clubteam-info');
    });
    {% if user.is_staff %}
    $("#refresh-btn").click( function() {
        $("#refresh-icon").addClass('icon-spin');
        $("#refresh-text").text('Refreshing...');
        $('#refresh-btn').attr("disabled", true);
        $.ajax({
            url: '{{ refresh_participation_stats }}', cache: false, success: function (result) {
                $("#participation-stats-table").html(result);
                $("#refresh-icon").removeClass('icon-spin');
                $("#refresh-text").text('Refresh');
                $('#refresh-btn').attr("disabled", false);
            }
        });
    });
    {% endif %}

</script>

{% endblock body_js %}