cshcsite/matches/urls.py
""" URL routing for views relating to matches.

    This includes all the RSS and ical feeds.
"""

from django.conf.urls import patterns, url
from matches import views, feeds

urlpatterns = patterns('',

    # E.g. '/matches/'                      - Searchable/filterable list of all matches
    url(r'^$',
        views.MatchListView.as_view(),
        name="match_list"
    ),

    # E.g. '/matches/23/'                   - Details of a specific match
    url(r'^(?P<pk>\d+)/$',
        views.MatchDetailView.as_view(),
        name="match_detail"
    ),

    # E.g. '/matches/23-Apr-13/'            - List of matches on a particular date
    url(r'^(?P<date>\d{2}-[a-zA-Z]{3}-\d{2})/$',
        views.MatchesByDateView.as_view(),
        name="matches_by_date"
    ),

    # E.g. '/matches/by-season/'            - Calendar view of matches in the current season
    url(r'^by-season/$',
        views.MatchesBySeasonView.as_view(),
        name="matches_by_season_default"
    ),

    # E.g. '/matches/by-season/2011-2012/'  - Calendar view of matches in a previous season
    url(r'^by-season/(?P<season_slug>[-\w]+)/$',
        views.MatchesBySeasonView.as_view(),
        name="matches_by_season"
    ),


    # E.g. '/matches/latest-results/'       - List of the latest result for each team
    url(r'^latest-results/$',
        views.LatestResultsView.as_view(),
        name="latest_results"
    ),

    # E.g. '/matches/next-fixtures/'        - List of the next fixture for each team
    url(r'^next-fixtures/$',
        views.NextFixturesView.as_view(),
        name="next_fixtures"
    ),

    # E.g. '/matches/appearances/23-Apr-13/'            - List of appearances on a particular date
    url(r'^appearances/(?P<date>\d{2}-[a-zA-Z]{3}-\d{2})/$',
        views.AppearancesByDateView.as_view(),
        name="appearances_by_date"
    ),


    # E.g. '/matches/goal-king/'            - Goal King table for the current season
    url(r'^goal-king/$',
        views.GoalKingSeasonView.as_view(),
        name="goal_king"
    ),

    # E.g. '/matches/goal-king/2011-2012/'  - Goal King table for previous seasons
    url(r'^goal-king/(?P<season_slug>[-\w]+)/$',
        views.GoalKingSeasonView.as_view(),
        name="goal_king_season"
    ),

    # E.g. '/matches/goal-king/2011-2012/ajax/'     - AJAX-only: Updates and refreshes Goal King stats
    url(r'^goal-king/(?P<season_slug>[-\w]+)/ajax/$',
        views.GoalKingSeasonUpdateView.as_view(),
        name="goal_king_season_update"
    ),

    # E.g. '/matches/accidental-tourist/'   - Accidental Tourist table for the current season
    url(r'^accidental-tourist/$',
        views.AccidentalTouristSeasonView.as_view(),
        name="accidental_tourist"
    ),

    # E.g. '/matches/accidental-tourist/2011-2012/'     - Accidental Tourist table for previous seasons
    url(r'^accidental-tourist/(?P<season_slug>[-\w]+)/$',
        views.AccidentalTouristSeasonView.as_view(),
        name="accidental_tourist_season"
    ),

    # E.g. '/matches/accidental-tourist/2011-2012/ajax/'    - AJAX-only: Updates and refreshes Accidental Tourist stats
    url(r'^accidental-tourist/(?P<season_slug>[-\w]+)/ajax/$',
        views.AccidentalTouristSeasonUpdateView.as_view(),
        name="accidental_tourist_season_update"
    ),

    # E.g. '/matches/naughty-step/'         - Statistics on the number of cards (red/yellow/green) received by members
    url(r'^naughty-step/$',
        views.NaughtyStepView.as_view(),
        name="naughty_step"
    ),

    # Feeds
    url(r'^feed/rss/$',                          # RSS feed of match reports
        feeds.RssMatchReportsFeed(),
        name="match_report_rss_feed"
    ),
    url(r'feed/atom/$',                         # Atom feed of match reports
        feeds.AtomMatchReportsFeed(),
        name="match_report_atom_feed"
    ),
    # E.g. '/matches/cshc_matches.ics'
    url(r'^cshc_matches.ics$',                  # Calendar feed of this season's matches
        feeds.MatchICalFeed(),
        name="match_ical_feed"
    ),
)

cshcsite/teams/urls.py
""" URL routing for views relating to teams.
"""

from django.conf.urls import patterns, url
from teams import views, feeds


urlpatterns = patterns('',

    # E.g. '/teams/'                            - List of all CSHC teams
    url(r'^/?$',
        views.ClubTeamListView.as_view(),
        name="clubteam_list"
    ),

    # E.g. '/teams/playing-record/'             - The playing records through the seasons of each team
    url(r'^playing-record/$',
        views.PlayingRecordView.as_view(),
        name="playing_record"
    ),

    # E.g. '/teams/playing-record/ajax/'        - AJAX-only: Updates and refreshes the playing records of each team
    url(r'^playing-record/ajax/$',
        views.PlayingRecordUpdateView.as_view(),
        name="playing_record_update"
    ),

    # E.g. '/teams/southerners/'                - Statistics table comparing the performance of CSHC teams this season
    url(r'^southerners/$',
        views.SouthernersSeasonView.as_view(),
        name="southerners_league"
    ),

    # E.g. '/teams/southerners/2011-2012/'      - Statistics table comparing the performance of CSHC teams in a previous season
    url(r'^southerners/(?P<season_slug>[-\w]+)/$',
        views.SouthernersSeasonView.as_view(),
        name="southerners_league_season"
    ),

    # E.g. '/teams/southerners/2011-2012/ajax/' - AJAX-only: Updates and refreshes the Southerners statistics
    url(r'^southerners/(?P<season_slug>[-\w]+)/ajax/$',
        views.SouthernersSeasonUpdateView.as_view(),
        name="southerners_league_season_update"
    ),

    # E.g. '/teams/m1/'                         - Details of a particular CSHC team (including the team's playing record) for the current season
    url(r'^(?P<slug>[-\w]+)/$',
        views.ClubTeamDetailView.as_view(),
        name="clubteam_detail"
    ),

    # E.g. '/teams/m1/2011-2012/'               - Details of a particular CSHC team (including the team's playing record) for a previous season
    url(r'^(?P<slug>[-\w]+)/(?P<season_slug>[-\w]+)/$',
        views.ClubTeamDetailView.as_view(),
        name="clubteam_season_detail"
    ),

    # E.g. /teams/m1.ics'                       - Calendar feed of a particular team's matches
    url(r'^(?P<slug>[-\w]+).ics$',
        feeds.ClubTeamMatchICalFeed(),
        name="clubteam_ical_feed"
    ),

    # E.g. /teams/m1.rss'                       - RSS feed of a particular team's match reports
    url(r'^(?P<slug>[-\w]+).rss$',
        feeds.RssClubTeamMatchReportsFeed(),
        name="clubteam_match_rss_feed"
    ),

    # E.g. '/teams/participation/23/ajax/'      - AJAX-only: Updates and refreshes the playing record stats for a particular team in a particular season
    url(r'^participation/(?P<participation_id>\d+)/ajax/$',
        views.ParticipationUpdateView.as_view(),
        name="participation_update"
    ),

    # E.g. '/teams/m1/stats/3/ajax/'             - AJAX-only: Retrieves fixture list, league table and squad membership for a particular team/season
    url(r'^(?P<slug>[-\w]+)/stats/(?P<season_pk>\d+)/ajax/$',
        views.ClubTeamStatsView.as_view(),
        name='clubteam_stats_ajax'),

    # E.g. '/teams/m1/stats/3/ajax/scrape/'      - AJAX-only: Scrapes the external league table website and updates and refreshes the league table for a particular team/season
    url(r'^(?P<slug>[-\w]+)/stats/(?P<season_pk>\d+)/ajax/scrape/$',
        views.ScrapeLeagueTableView.as_view(),
        name='refresh_league_table'),

)

cshcsite/matches/models/appearance.py
""" The Appearance model is used to track which members (players)
    played in a match and how many goals they scored, cards they
    received etc.
"""

from django.db import models
from django.db.models.query import QuerySet
from model_utils.managers import PassThroughManager
from members.models import Member
from matches.models.match import Match


class AppearanceQuerySet(QuerySet):
    """ Queries that relate to an appearance"""

    def by_member(self, member):
        """ Returns only the appearances for a specific member"""
        return self.filter(member=member)

    def by_season(self, season):
        """ Returns only the appearances for a particular season"""
        return self.select_related('match__season').filter(match__season=season)


class Appearance(models.Model):
    """ Represents an appearance by a member in a match.
        This model also holds information on goals scored (incl own
        goals), and cards received.
    """
    # The person making the appearance
    member = models.ForeignKey(Member, related_name="appearances")

    # The match in which the member played
    match = models.ForeignKey(Match, related_name="appearances")

    # The number of goals the player scored
    goals = models.PositiveSmallIntegerField("Goals scored", default=0)

    # The number of own-goals the player scored
    own_goals = models.PositiveSmallIntegerField("Own-goals scored", default=0)

    # The following are nullable as we won't have this information for archive data                                   
    green_card_count = models.PositiveSmallIntegerField(default=0, null=True, blank=True, 
                                         help_text="The number of green cards the player received in the match")
    yellow_card_count = models.PositiveSmallIntegerField(default=0, null=True, blank=True, 
                                          help_text="The number of yellow cards the player received in the match")
    red_card = models.NullBooleanField(default=False,
                                       help_text="Did the player receive a red card in the match?")
    
    objects = PassThroughManager.for_queryset_class(AppearanceQuerySet)()

    class Meta:
        """ Meta-info for the Appearance model."""
        app_label = 'matches'
        # A player can only make one appearance in a match!
        unique_together = ('member', 'match')
        ordering = ['match', 'member']

    def __unicode__(self):
        return unicode("{} - {}".format(self.member, self.match))

    def green_card_range(self):
        return range(self.green_card_count or 0);

    def yellow_card_range(self):
        return range(self.yellow_card_count or 0);

cshcsite/matches/models/match_commentary.py
# During a match, people can use the website to add 'live commentary'
# on the proceedings, including goals scored/conceeded, regular text
# updates and photos. The MatchComment model captures a single (timestamped)
# comment. Comments are always associated with a particular match and
# an 'author' (only logged in users can post comments).

# To avoid multiple people recording that a goal was scored,
# one person and only one person can be the official match commentator.
# Initially when the match page is viewed, if you are logged in you
# will have an option to make yourself the match commentator. After
# this point, no-one else will be able to make themselves match commentator.
# You will then have additional priviledges and options (e.g. to record
# goals scored/conceeded and to delete comments). At any time that person
# can relinquish his/her role as commentator - at which point someone
# else could take over.

from django.db import models
from django.core.exceptions import ValidationError
from django.db.models.query import QuerySet
from model_utils.managers import PassThroughManager
from model_utils import Choices
from core.models import is_none_or_empty, CshcUser
from matches.models import Match



class MatchCommentQuerySet(QuerySet):
    """ Queries that relate to Matches"""

    def by_author(self, author):
        return self.filter(author=author)

    def by_match(self, match_id):
        return self.filter(match__id=match_id)

    def since(self, match_id, last_update):
        return self.filter(match__id=match_id, timestamp__gt=last_update)


class MatchComment(models.Model):

    COMMENT_TYPE = Choices((0, 'Scored', 'Goal scored'),
                           (1, 'Conceeded', 'Goal conceeded'),
                           (2, 'Photo', 'Photo'),
                           (3, 'Update', 'Update'))

    STATE = Choices('Pending', 'Approved', 'Rejected', 'Deleted')

    author = models.ForeignKey(CshcUser, null=True, blank=True, on_delete=models.SET_NULL)
    match = models.ForeignKey(Match)

    comment_type = models.IntegerField("Comment Type", choices=COMMENT_TYPE, default=COMMENT_TYPE.Update)

    comment = models.TextField("Comment", blank=True)

    # An optional photo
    photo = models.ImageField("Photo", upload_to='uploads/match_photos', null=True, blank=True)

    state = models.CharField("State", max_length=10, choices=STATE, default=STATE.Approved)

    # Automatically created attribute
    timestamp = models.DateTimeField("Timestamp", auto_now_add=True, editable=False)
    last_modified = models.DateTimeField("Last modified", auto_now=True, editable=False)

    objects = PassThroughManager.for_queryset_class(MatchCommentQuerySet)()

    class Meta:
        app_label = 'matches'
        ordering = ['-timestamp']

    def clean(self):
        if self.comment_type == MatchComment.COMMENT_TYPE.Update and is_none_or_empty(self.comment):
            raise ValidationError("A comment must be supplied for an 'update' match comment")

        if self.comment_type == MatchComment.COMMENT_TYPE.Photo and self.photo is None:
            raise ValidationError("A photo must be supplied for a 'photo' match comment")

    def __unicode__(self):
        return unicode("{}: {} ({})".format(self.timestamp.strftime('%X %x'), self.get_comment_type_display(), self.author))

cshcsite/matches/forms.py
""" Custom forms relating to matches.
"""

from django import forms
from redactor.widgets import RedactorEditor
from matches.models import Match

class MatchForm(forms.ModelForm):
    """ A form for entering match details.
        A Redactor widget is specified for editing the Pre-Match Hype
        and Report Body fields.

        Ref: https://github.com/TigorC/django-redactorjs
    """
    class Meta:
        """ Meta-info for the form."""
        model = Match
        widgets = {
            'pre_match_hype': RedactorEditor(upload_to="uploads/match_reports/",
                                             redactor_options={'minHeight': 150}),
            'report_body': RedactorEditor(upload_to="uploads/match_reports/",
                                          redactor_options={'minHeight': 400})
        }

cshcsite/training/forms.py
""" Custom forms related to training sessions.
"""

import logging
from datetime import timedelta, datetime
from django import forms
from training.models import TrainingSession
from venues.models import Venue

LOG = logging.getLogger(__name__)

MULTIPLE = 'M'
UNTIL = 'U'
REPEAT_CHOICES = (
    (MULTIPLE, "Multiple"),
    (UNTIL, "Until")
)

DATE_INPUT_FORMATS = ['%Y-%m-%d', '%d/%m/%Y', '%d-%m-%Y', '%d/%m/%y', '%d-%m-%y']
TIME_INPUT_FORMATS = ['%H:%M']

class TrainingSessionForm(forms.Form):
    """ A custom form for adding multiple training sessions. """
    venue = forms.ModelChoiceField(queryset=Venue.objects.home_venues())
    description = forms.CharField(min_length=2, max_length=200)
    duration_mins = forms.IntegerField(min_value=10, max_value=480, initial=90)  # Prevent silly numbers
    datetime = forms.SplitDateTimeField(input_date_formats=DATE_INPUT_FORMATS,
                                        input_time_formats=TIME_INPUT_FORMATS, initial=datetime.now())
    repeat = forms.BooleanField(initial=True, required=False)
    repeat_option = forms.ChoiceField(choices=REPEAT_CHOICES,
                                      widget=forms.RadioSelect)
    repeat_count = forms.IntegerField(min_value=2, max_value=52, initial=10, required=False)
    repeat_until = forms.DateField(input_formats=DATE_INPUT_FORMATS, required=False)

    def save_training_sessions(self):
        """ Save the training sessions specified by the form data. """
        print self.cleaned_data
        if self.cleaned_data['repeat']:
            # Save multiple training sessions
            sessions = []
            if self.cleaned_data['repeat_option'] == MULTIPLE:
                LOG.info("Saving {} repeated training sessions".format(self.cleaned_data['repeat_count']))
                for i in range(0, self.cleaned_data['repeat_count']):
                    sessions.append(self.new_session(i))
            else:
                LOG.info("Saving repeated training sessions up to {}".format(self.cleaned_data['repeat_until']))
                week_offset = 0
                start_date = self.cleaned_data['datetime'].date()
                end = self.cleaned_data['repeat_until']
                while end > (start_date + timedelta(days=week_offset*7)):
                    sessions.append(self.new_session(week_offset))
                    week_offset += 1
            return sessions

        else:
            LOG.info("Saving a single training session")
            return [self.new_session(0)]


    def new_session(self, week_offset):
        """ Adds a new training session at the specified week offset. """
        session = TrainingSession()
        session.venue = self.cleaned_data['venue']
        session.description = self.cleaned_data['description']
        session.datetime = self.cleaned_data['datetime'] + timedelta(days=week_offset*7)
        session.duration_mins = self.cleaned_data['duration_mins']
        session.save()
        return session

    # class Meta:
    #     """ Meta-info for the form. """
    #     model = TrainingSession
    #     widgets = {
    #         'datetime': DateTimeWidget(attrs={'id':"id_datetime"}, bootstrap_version=2)
    #     }

cshcsite/templates/matches/_accidental_tourist_table.html
{% load core_tags %}

<table class="table table-condensed table-hover table-center-align">
    <thead>
        <tr><th>Rank</th>
        <th class="left-align">Name</th>
        <th class="priority2"><abbr title="Total games played">Played</abbr></th>
        <th><abbr title="Total miles travelled">Miles</abbr></th>
        <th><abbr title="Miles per game">MPG</abbr></th>
        </tr>
    </thead>
    <tbody>
    {% for gk in goalking_list %}
        <tr>
            <td><span class="label label-{{ gk.member.gender|lower }}">{{ gk.rank }}</span></td>
            <td class="left-align">{{ gk.member|urlise_model }}</td>
            <td class="priority2">{{ gk.games_played|default:"" }}</td>
            <td>{{ gk.total_miles }}</td>
            <td>{{ gk.miles_per_game|floatformat:1 }}</td>
    {% endfor %}
    </tbody>
</table>

cshcsite/templates/matches/_date_pager.html
{% comment %}
Adds next date and prev date links to a page.
Expects 'next_date' and 'prev_date' context times (dates)
Also expects 'next_date_url' and 'prev_date_url' and 'title'
{% endcomment %}

<ul class="pager">
    {% if prev_date %}
        <li class="previous{% if not prev_date %} disabled{% endif %}">
            <a href="{% if prev_date %}{{ prev_date_url }}{% else %}#{% endif %}" {% if prev_date %}title="{{ title }} on {{ prev_date|date:"jS F Y" }}"{% endif %}>&larr; {{ prev_date|date:"jS N Y" }}</a>
        </li>
    {% endif %}
    {% if next_date %}
        <li class="next{% if not next_date %} disabled{% endif %}">
            <a href="{% if next_date %}{{ next_date_url }}{% else %}#{% endif %}" {% if next_date %}title="{{ title }} on {{ next_date|date:"jS F Y" }}"{% endif %}>{{ next_date|date:"jS N Y" }} &rarr;</a>
        </li>
    {% endif %}
</ul>

cshcsite/templates/matches/match_list.html
{% extends "base.html" %}

{% load core_tags %}
{% load i18n %}
{% load pagination_tags %}
{% load sorter_tags %}

{% comment %}
Filter-able, sortable, paginated display of matches.
{% endcomment %}

{% block title %}{{ block.super }} | Matches{% endblock %}

{% block body_id %}match-list{% endblock body_id %}

{% block content %}

{% url 'match_list' as match_list_url %}

<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Matches</li>
</ul>

<div class="page-header">
    <h1>Match search</h1>
</div>

<p class="lead">Use the filters below to find exactly the matches you're looking for!</p>

     <div class="row" id="filter">
        <div class="span12"><h4>Filter</h4></div>
        <form action="" method="get">
        <div class="span12">{{ filter.form.non_field_errors }}</div>
        <div class="span4">
            <div class="fieldWrapper">
                {{ filter.form.our_team.errors }}
                <label for="id_our_team">Our team:</label>
                {{ filter.form.our_team }}
            </div>
            <div class="fieldWrapper">
                {{ filter.form.opp_team.errors }}
                <label for="id_opp_team">Opposition:</label>
                {{ filter.form.opp_team }}
            </div>
            <div class="fieldWrapper">
                {{ filter.form.date.errors }}
                <label for="id_date">Date:</label>
                {{ filter.form.date }}
            </div>
            <div class="fieldWrapper">
                {{ filter.form.venue.errors }}
                <label for="id_venue">Venue:</label>
                {{ filter.form.venue }}
            </div>
        </div>
        <div class="span4">
            <div class="fieldWrapper">
                {{ filter.form.season.errors }}
                <label for="id_season">Season:</label>
                {{ filter.form.season }}
            </div>
            <div class="fieldWrapper">
                {{ filter.form.division.errors }}
                <label for="id_division">Division:</label>
                {{ filter.form.division }}
            </div>
            <div class="fieldWrapper">
                {{ filter.form.home_away.errors }}
                <label for="id_home_away">Home/Away:</label>
                {{ filter.form.home_away }}
            </div>
            <div class="fieldWrapper">
                {{ filter.form.fixture_type.errors }}
                <label for="id_fixture_type">Fixture type:</label>
                {{ filter.form.fixture_type }}
            </div>
        </div>
        <div class="span4">
            <div class="fieldWrapper players">
                {{ filter.form.players.errors }}
                <label id="label_players" for="id_players">Players:</label>
                {{ filter.form.players }}
            </div>
        </div>
        <div class="span12"><input class="btn btn-primary" type="submit" /><input class="btn" type="reset" value="Reset" /></div>
    </div>
    </form>

    <hr/>
    {% sort filter.qs as sorted_list %}
    {% autopaginate sorted_list 20 as sorted_filter_list %}

    {% if sorted_filter_list %}
        <table id="matches" class="table">
            <thead>
                <tr>
                    <th class="priority3"></th>
                    <th>{% sortlink by "date" "-date" %}Date{% endsortlink %}</th>
                    <th>{% sortlink by "our_team" "-our_team" %}Team{% endsortlink %}</th>
                    <th>Score</th>
                    <th>{% sortlink by "opp_team" "-opp_team" %}Opposition{% endsortlink %}</th>
                    <th class="priority2">{% sortlink by "venue" "-venue" %}Venue{% endsortlink %}</th>
                    <th></th>
                </tr>
            </thead>
            {% for match in sorted_filter_list %}
                <tr>
                    <td class="priority3">{% include 'matches/_fixture_icon.html' %}</td>
                    <td class="no-break"><a title="Matches on {{ match.date|date:"jS M Y" }}" href="{% url 'matches_by_date' match.date|date:"d-M-y"%}">{{ match.date|date:"jS M Y" }}</a></td>
                    <td><a href="{{ match.our_team.get_absolute_url }}">{{ match.our_team.short_name }}</a></td>
                    <td>{{ match.score_display }}</td>
                    <td><a href="{{ match.opp_team.club.get_absolute_url }}">{{ match.opp_team.genderless_name }}</a></td>
                    <td class="priority2">{% if match.venue %}<a href="{{ match.venue.get_absolute_url }}" title="{{ match.venue.name }}">{{ match.simple_venue_name }}</a>{% elif match.is_in_past %}???{% else %}<abbr title="Venue not known">TBD</abbr>{% endif %}</a></td>
                    <td>{% include 'core/_match_link.html' %}</td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p class="lead muted">No matches found!</p>
    {% endif %}

    {% paginate %}

    {% model_admin_links 'matches' 'match' %}

{% endblock content %}

cshcsite/templates/matches/matches_by_date.html
{% extends "base.html" %}
{% load core_tags %}
{% load disqus_tags %}

{% comment %}
Formatted display of matches on a particular date.
- Used by club.views.matches.by_date
Currently just lists the values that will be needed by this template - no UI design here yet!
{% endcomment %}

{% block title %}{{ block.super }} | Matches on {{ date|date:"jS M Y" }}{% endblock %}

{% block body_id %}matches-by-date{% endblock body_id %}

{% block content %}
{% url 'match_list' as match_list_url %}

<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li><a href="{{ match_list_url }}">Matches</a> <span class="divider">/</span></li>
  <li class="active">{{ date|date:"jS M Y" }}</li>
</ul>

<div class="page-header">
    <h1>Matches <small>{{ date|date:"jS M Y" }}</small></h1>
</div>

{% url 'matches_by_date' prev_date|date:"d-M-y" as prev_date_url %}
{% url 'matches_by_date' next_date|date:"d-M-y" as next_date_url %}
{% include 'matches/_date_pager.html' with title="Matches" %}

{% for m in match_list %}
    <a class="match-link" href="{{ m.match.get_absolute_url }}" title="Match details">
        <div class="row match-score">
            <div class="team-name">
                {{ m.match.our_team.abbr_name }}
            </div>
            {% if m.match.final_scores_provided %}
            <div class="team-score">
                {{ m.match.our_score }} - {{ m.match.opp_score }}
            </div>
            {% elif m.match.is_off %}
            <div class="team-score alt-score">
                {{ m.match.get_alt_outcome_display }}
            </div>
            {% else %}
            <div class="team-score">
                vs
            </div>
            {% endif %}
            <div class="team-name">
                {{ m.match.opp_team.name }}
            </div>
        </div>
    </a>
    
    <div class="row match-detail">
        {% if m.match.is_in_past %}
            <div class="span12">
                <div class="match-content past-match">
                    <ul class="inline">
                        {% if m.mom_winners %}
                            <li><i class="icon icon-star"></i>
                            {% for mom in m.mom_winners %}
                                <a href="{{ mom.member.get_absolute_url }}" title="{{ mom.comment }}">{{ mom.member.first_name_and_initial }}</a>{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                            </li>
                        {% endif %}
                        {% if m.lom_winners %}
                            <li><i class="icon icon-lemon"></i>
                            {% for lom in m.lom_winners %}
                                <a href="{{ lom.member.get_absolute_url }}" title="{{ lom.comment }}">{{ lom.member.first_name_and_initial }}</a>{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                            </li>
                        {% endif %}
                        {% if m.scoring_appearances %}
                            <li><strong>Scorers:</strong>
                            {% for scorer in m.scoring_appearances %}
                                <a href="{{ scorer.member.get_absolute_url }}">{{ scorer.member.first_name_and_initial }}</a>{% if scorer.goals > 1 %}({{ scorer.goals }}){% endif %}{% if not forloop.last %}, {% endif %}
                            {% endfor %}
                            </li>
                        {% endif %}
                    </ul>
                    <h4>{{ m.match.match_title_text }}</h4>
                    {{ m.match.report_body.excerpt|safe }}
                    {% if m.match.report_body.has_more %}
                        <p class="pull-right"><a class="btn btn-mini btn-success" href="{{ m.match.get_absolute_url }}" title="Match details">Continue reading...</a></p>
                    {% endif %}
                    <p><i class="icon-comment"></i><a href="{{ m.match.get_absolute_url }}#disqus_thread" data-disqus-identifier="match_{{ m.match.pk }}">View Comments</a></p>
                    {% disqus_num_replies %}
                </div>
            </div>
        {% else %}
            <div class="span7">
                <div class="match-content future-match">
                    <ul class="inline">
                        <li><i class="icon icon-time"></i>{{ m.match.time_display }}</li>
                        <li><i class="icon icon-map-marker"></i>{% if m.match.venue %}{{ m.match.venue|urlise_model }}{% else %}TBD{% endif %}</li>
                        {% if m.match.division %}<li><i class="icon icon-table"></i>{{ m.match.division }}</li>{% endif %}
                    </ul>
                    {{ m.match.pre_match_hype.excerpt|safe }}
                    {% if m.match.pre_match_hype.has_more %}
                        <p class="pull-right"><a class="btn btn-mini btn-success" href="{{ m.match.get_absolute_url }}" title="Match details">Continue reading...</a></p>
                    {% endif %}
                    <p><i class="icon-comment"></i><a href="{{ m.match.get_absolute_url }}#disqus_thread" data-disqus-identifier="match_{{ m.match.pk }}">View Comments</a></p>
                    {% disqus_num_replies %}
                </div>
            </div>
            <div class="span5">
                {% if m.match.venue and m.match.venue.address_known %}
                    <div class="gmap3 map_small" id="map_canvas{{ forloop.counter0 }}"></div>
                {% endif %}
            </div>
        {% endif %}
    </div>

{% empty %}
    <p class="muted">No matches on this date</p>
{% endfor %}

{% include 'matches/_date_pager.html' with title="Matches" %}

{% if perms.matches.add_appearance %}
{% url 'appearances_by_date' date|date:"d-M-y" as appearances_url %}
<a class="btn btn-default" href="{{ appearances_url }}" title="View all appearances on this date">View all appearances</a>
{% endif %}

{% endblock %}

{% block body_js %}
    {{ block.super }}
    {% include "matches/_match_list_map_js.html" %}
{% endblock body_js %}