cshcsite/teams/urls.py
""" URL routing for views relating to teams.
"""

from django.conf.urls import patterns, url
from teams import views, feeds


urlpatterns = patterns('',

    # E.g. '/teams/'                            - List of all CSHC teams
    url(r'^/?$',
        views.ClubTeamListView.as_view(),
        name="clubteam_list"
    ),

    # E.g. '/teams/playing-record/'             - The playing records through the seasons of each team
    url(r'^playing-record/$',
        views.PlayingRecordView.as_view(),
        name="playing_record"
    ),

    # E.g. '/teams/playing-record/ajax/'        - AJAX-only: Updates and refreshes the playing records of each team
    url(r'^playing-record/ajax/$',
        views.PlayingRecordUpdateView.as_view(),
        name="playing_record_update"
    ),

    # E.g. '/teams/southerners/'                - Statistics table comparing the performance of CSHC teams this season
    url(r'^southerners/$',
        views.SouthernersSeasonView.as_view(),
        name="southerners_league"
    ),

    # E.g. '/teams/southerners/2011-2012/'      - Statistics table comparing the performance of CSHC teams in a previous season
    url(r'^southerners/(?P<season_slug>[-\w]+)/$',
        views.SouthernersSeasonView.as_view(),
        name="southerners_league_season"
    ),

    # E.g. '/teams/southerners/2011-2012/ajax/' - AJAX-only: Updates and refreshes the Southerners statistics
    url(r'^southerners/(?P<season_slug>[-\w]+)/ajax/$',
        views.SouthernersSeasonUpdateView.as_view(),
        name="southerners_league_season_update"
    ),

    # E.g. '/teams/m1/'                         - Details of a particular CSHC team (including the team's playing record) for the current season
    url(r'^(?P<slug>[-\w]+)/$',
        views.ClubTeamDetailView.as_view(),
        name="clubteam_detail"
    ),

    # E.g. '/teams/m1/2011-2012/'               - Details of a particular CSHC team (including the team's playing record) for a previous season
    url(r'^(?P<slug>[-\w]+)/(?P<season_slug>[-\w]+)/$',
        views.ClubTeamDetailView.as_view(),
        name="clubteam_season_detail"
    ),

    # E.g. /teams/m1.ics'                       - Calendar feed of a particular team's matches
    url(r'^(?P<slug>[-\w]+).ics$',
        feeds.ClubTeamMatchICalFeed(),
        name="clubteam_ical_feed"
    ),

    # E.g. /teams/m1.rss'                       - RSS feed of a particular team's match reports
    url(r'^(?P<slug>[-\w]+).rss$',
        feeds.RssClubTeamMatchReportsFeed(),
        name="clubteam_match_rss_feed"
    ),

    # E.g. '/teams/participation/23/ajax/'      - AJAX-only: Updates and refreshes the playing record stats for a particular team in a particular season
    url(r'^participation/(?P<participation_id>\d+)/ajax/$',
        views.ParticipationUpdateView.as_view(),
        name="participation_update"
    ),

    # E.g. '/teams/m1/stats/3/ajax/'             - AJAX-only: Retrieves fixture list, league table and squad membership for a particular team/season
    url(r'^(?P<slug>[-\w]+)/stats/(?P<season_pk>\d+)/ajax/$',
        views.ClubTeamStatsView.as_view(),
        name='clubteam_stats_ajax'),

    # E.g. '/teams/m1/stats/3/ajax/scrape/'      - AJAX-only: Scrapes the external league table website and updates and refreshes the league table for a particular team/season
    url(r'^(?P<slug>[-\w]+)/stats/(?P<season_pk>\d+)/ajax/scrape/$',
        views.ScrapeLeagueTableView.as_view(),
        name='refresh_league_table'),

)

cshcsite/core/models/club_info.py
""" A simple key-value dictionary stored in the database.
"""

from django.db import models


class ClubInfo(models.Model):
    """ This model is used as a look-up table for club information where the actual
        value may change over time and needs to be easily editable through the admin backend
        without modification to the templates or Python code that reference it.
    """

    key = models.CharField(max_length=20, unique=True)
    """ The look-up key. The value of this field is what is referenced directly in
    template and Python code."""

    value = models.CharField(max_length=100)
    """ The lookup value. This is the actual value that is required by the templates
    or Python code."""

    class Meta:
        """ Meta-info for the ClubInfo model. """
        app_label = 'core'
        verbose_name = 'Club Information'
        verbose_name_plural = 'Club Information'
        ordering = ['key']

    def __unicode__(self):
        return unicode("{}: {}".format(self.key, self.value))

cshcsite/core/models/contact_submission.py
""" Storage of 'Contact Us' form submissions.
"""

from django.db import models


class ContactSubmission(models.Model):
    """This model is used to store submitted contact form details"""

    # Required attributes:
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.EmailField("email address")
    mailing_list = models.BooleanField("Add to mailing list", default=False,
                                       help_text="If you select 'yes', we'll add you to our club mailing list. Don't worry - its easy to unsubscribe too!")

    # Optional attributes:
    phone = models.CharField("Phone number", max_length=30, blank=True)
    message = models.TextField("Message", help_text="Message (comments/questions etc)")
    our_notes = models.TextField(blank=True, help_text="Any notes from the club about this enquiry")

    # Automatically created attributes
    submitted = models.DateTimeField("Date submitted", auto_now_add=True, editable=False)

    class Meta:
        """ Meta-info for the ContactSubmission model. """
        app_label = 'core'
        ordering = ['submitted']

    def __unicode__(self):
        return unicode("{} ({})".format(self.full_name(), self.submitted))

    def full_name(self):
        """ Full name of the person making the enquiry"""
        return u"{} {}".format(self.first_name, self.last_name)

cshcsite/core/models/util.py
""" Common model utility methods.
"""

import uuid
from django.conf import settings
from model_utils import Choices


def make_unique_filename(filename):
    """ Produces a unique filename, combining the given filename
        and a uuid.
    """
    ext = filename.split('.')[-1]
    return "%s.%s" % (uuid.uuid4(), ext)


def is_none_or_empty(string):
    """ Given a string, returns True if the string is equal to None and is not empty"""
    return string is None or string.strip() == ""


def not_none_or_empty(string):
    """ Given a string, returns True if the string is not equal to None and is not empty"""
    return not is_none_or_empty(string)

# Enumeration of choices for a team's gender. Used in multiple apps.
TeamGender = Choices('Mens', 'Ladies', 'Mixed')

# Enumeration of choices for a team's ordinal. Used in multiple apps.
TeamOrdinal = Choices(
        ('T1', '1sts'),
        ('T2', '2nds'),
        ('T3', '3rds'),
        ('T4', '4ths'),
        ('T5', '5ths'),
        ('T6', '6ths'),
        ('T7', '7ths'),
        ('T8', '8ths'),
        ('T9', '9ths'),
        ('T10', '10ths'),
        ('T11', '11ths'),
        ('T12', '12ths'),
        ('TVets', 'Vets'),
        ('TIndoor', 'Indoor'),
        ('TOther', 'Other'))


def ordinal_from_TeamOrdinal(team_ordinal):
    """ Given a team ordinal, returns the actual ordinal part (stripping off the leading 'T')"""
    return team_ordinal.lstrip('T')

def splitify(text):
    """ Ensures a SPLIT_MARKER is inserted after the first paragraph of text.
        Returns the text with the SPLIT_MARKER.

        Ref: https://django-model-utils.readthedocs.org/en/latest/fields.html#splitfield
    """
    if text:
        if not settings.SPLIT_MARKER in text:
            if '</p><p>' in text:
                text = text.replace('</p><p>', '</p>\r\n{}\r\n<p>'.format(settings.SPLIT_MARKER), 1)
    return text

cshcsite/core/views.py
""" Common Django views and view utilities
"""

import logging
from datetime import timedelta
from django.views.generic import TemplateView, FormView
from django.views.generic.edit import CreateView
from django.shortcuts import render_to_response
from django.contrib import messages
from django.template import RequestContext
from django.contrib.sites.models import Site
from django.conf import settings
from django.utils.decorators import method_decorator
from django.contrib.sites.models import RequestSite
from templated_emails.utils import send_templated_email
from registration import signals as reg_signals
from registration.views import RegistrationView as BaseRegistrationView
from competitions.models import Season
from core.models import ClubInfo, ContactSubmission, JuniorsContactSubmission
from core.forms import ContactSubmissionForm, UserCreationForm, JuniorsContactSubmissionForm
from core.reg_utils import create_inactive_user

LOG = logging.getLogger(__name__)


def get_season_from_kwargs(kwargs):
    """ Many URLs have an optional 'season_slug' parameter, specifying
        a particular season. If not specified, we default to the current
        season.
    """
    season_slug = kwargs_or_none('season_slug', **kwargs)
    if season_slug is not None:
        season = Season.objects.get(slug=season_slug)
    else:
        season = Season.current()
    return season

def add_season_selector(context, season, season_list):
    """ Adds season information to the given context, facilitating
        the use of the core/_season_selector.html template.

        Returns the updated context.
    """
    context['season'] = season
    context['season_list'] = season_list
    context['is_current_season'] = Season.is_current_season(season.id)
    return context

def is_prod_site():
    """ Utility method to check if this is the production site."""
    return 'cambridgesouthhockeyclub' in Site.objects.get_current().domain

def saturdays_in_season(season):
    """ Gets a list of all the Saturdays (match days) in the given season. """
    return saturdays_in_range(season.start, season.end)

def saturdays_in_range(start, end):
    """ Gets a list of all the Saturdays (match days) in the given range. """
    sats = []
    sat = _first_sat(start)
    while sat <= end:
        sats.append(sat)
        sat += timedelta(days=7)

    return sats

def _first_sat(dt):
    """ Gets the first Saturday following the given date. """
    while dt.weekday() < 5:
        dt = dt + timedelta(days=1)
    return dt

def valid_kwarg(key, **dict):
    """ Given a key and a dictionary, returns True if the given key is in
        the dictionary and its value is not None or an empty string.
    """
    return key in dict and dict[key] is not None and dict[key] != ""

def kwargs_or_none(key, **dict):
    """ Given a key and a dictionary, returns the key's value, or None
        if the key is not valid.
    """
    if valid_kwarg(key, **dict):
        return dict[key]
    else:
        return None

def add_clubinfo_to_context(context):
    """ Adds all ClubInfo instances to the given context. """
    context['clubinfo'] = ClubInfo.objects.all()

def ajax_request(function):
    """ Used as a method decorator.
        Given a request, checks if the request is an AJAX request.
        If not, the 'AJAX required' error template is rendered.
        Otherwise the wrapped function is called.
    """
    def wrapper(request, *args, **kwargs):
        """ Returns error response if request is not AJAX. """
        if not request.is_ajax():
            return render_to_response('error/ajax_required.html', {},
                                      context_instance=RequestContext(request))
        else:
            return function(request, *args, **kwargs)
    return wrapper


class AjaxGeneral(TemplateView):
    """ Base template view for AJAX views.
        All views are wrapped by a call that ensures the request is an AJAX request.
    """
    template_name = None

    def get(self, request, *args, **kwargs):
        data = self.get_template_context(**kwargs)
        return render_to_response(self.template_name, data,
                                  context_instance=RequestContext(request))

    def get_template_context(self, **kwargs):
        """ Return the template context."""
        msg = "{0} is missing get_template_context.".format(self.__class__)
        raise NotImplementedError(msg)

    @method_decorator(ajax_request)
    def dispatch(self, *args, **kwargs):
        return super(AjaxGeneral, self).dispatch(*args, **kwargs)


class ContactSubmissionCreateView(CreateView):
    """ This is essentially the 'Contact Us' form view. """

    model = ContactSubmission
    form_class = ContactSubmissionForm
    template_name = "core/contact.html"
    success_url = '/contact/'

    def email_to_secretary(self, form):
        """ Send an email to the secretary with the form data. """
        email = form.cleaned_data['email']
        LOG.debug("Email = {}".format(email))
        context = {
            'name': u"{} {}".format(form.cleaned_data['first_name'], form.cleaned_data['last_name']),
            'phone': form.cleaned_data['phone'],
            'sender_email': email,
            'join_mail_list': form.cleaned_data['mailing_list'],
            'message': unicode(form.cleaned_data['message']),
        }

        try:
            recipient_email = ClubInfo.objects.get(key='SecretaryEmail').value
        except ClubInfo.DoesNotExist:
            recipient_email = 'secretary@cambridgesouthhockeyclub.co.uk'
        send_templated_email([recipient_email], 'emails/contact_secretary',
                             context, from_email=email)

    def email_to_enquirer(self, form):
        """ Send a confirmation email to the person submitting the form. """
        context = {
            'first_name': unicode(form.cleaned_data['first_name']),
            'message': unicode(form.cleaned_data['message']),
        }
        try:
            context['secretary_name'] = ClubInfo.objects.get(key='SecretaryName').value
            context['secretary_email'] = ClubInfo.objects.get(key='SecretaryEmail').value
        except ClubInfo.DoesNotExist:
            context['secretary_name'] = ""
            context['secretary_email'] = 'secretary@cambridgesouthhockeyclub.co.uk'

        recipient_email = form.cleaned_data['email']
        send_templated_email([recipient_email], 'emails/contact_sender',
                             context, from_email=context['secretary_email'])

    def form_valid(self, form):
        try:
            self.email_to_secretary(form)
            self.email_to_enquirer(form)
            messages.info(self.request, "Thanks for your message. We'll be in touch shortly!")
        except:
            LOG.warn("Failed to send contact us email", exc_info=True)
            messages.error(self.request, "Sorry - we were unable to send your message. Please try again later.")
        return super(ContactSubmissionCreateView, self).form_valid(form)



class JuniorsContactSubmissionCreateView(CreateView):
    """ This is the enquery form for juniors. """

    model = JuniorsContactSubmission
    form_class = JuniorsContactSubmissionForm
    template_name = "core/juniors.html"
    success_url = '/juniors/'

    def email_to_juniors(self, form):
        """ Send an email to juniors@cambridgesouthhockeyclub.co.uk with the form data. """
        email = form.cleaned_data['email']
        trigger = form.cleaned_data['trigger']
        triggerText = JuniorsContactSubmission.TRIGGER[trigger] if trigger != JuniorsContactSubmission.TRIGGER.not_selected else None
        LOG.debug("Email = {}".format(email))
        context = {
            'name': u"{} {}".format(form.cleaned_data['first_name'], form.cleaned_data['last_name']),
            'phone': form.cleaned_data['phone'],
            'sender_email': email,
            'child_name': form.cleaned_data['child_name'],
            'child_age': JuniorsContactSubmission.AGE[form.cleaned_data['child_age']],
            'child_gender': JuniorsContactSubmission.GENDER[form.cleaned_data['child_gender']],
            'trigger': triggerText,
            'join_mail_list': form.cleaned_data['mailing_list'],
            'message': unicode(form.cleaned_data['message']),
        }

        recipient_email = 'juniors@cambridgesouthhockeyclub.co.uk'
        send_templated_email([recipient_email], 'emails/juniors_report',
                             context, from_email=email)

    def email_to_enquirer(self, form):
        """ Send a confirmation email to the person submitting the form. """
        context = {
            'first_name': unicode(form.cleaned_data['first_name']),
            'message': unicode(form.cleaned_data['message']),
        }

        recipient_email = form.cleaned_data['email']
        send_templated_email([recipient_email], 'emails/juniors_sender',
                             context, from_email='juniors@cambridgesouthhockeyclub.co.uk')

    def form_valid(self, form):
        try:
            self.email_to_juniors(form)
            self.email_to_enquirer(form)
            messages.info(self.request, "Thanks for your message. We'll be in touch shortly!")
        except:
            LOG.warn("Failed to send juniors email", exc_info=True)
            messages.error(self.request, "Sorry - we were unable to send your message. Please try again later.")
        return super(JuniorsContactSubmissionCreateView, self).form_valid(form)



# Copied and modified from registration.backends.default.views
class RegistrationView(BaseRegistrationView):
    """
    A registration backend which follows a simple workflow:

    1. User signs up, inactive account is created.

    2. Email is sent to user with activation link.

    3. User clicks activation link, account is now active.

    Using this backend requires that

    * ``registration`` be listed in the ``INSTALLED_APPS`` setting

cshcsite/templates/core/_admin_link.html
{% comment %}
Link to be put on the front-end that points to the admin back-end that corresponds
to the content being displayed.

Requires 'app_label' and 'model' variables

Requires at least one of:
   'edit_url' - the admin url for editing an item
   'add_url' - the admin url for adding an item
   'list_url' - the admin url for displaying the list of items
{% endcomment %}

{% if user.is_staff %}
{% if display_admin_links %}

<div class="admin-links">
  <div class="btn-group">
    <a class="btn btn-success dropdown-toggle" data-toggle="dropdown" href="#" title="Admin actions"><i class="icon-edit"></i><span class="caret"></span></a>
    <ul class="dropdown-menu">
      {% if change_url %}<li><a href="{{ change_url }}" target="_blank">{% if change_label %}{{ change_label }}{% else %}Edit{% endif %}</a></li>{% endif %}
      {% if add_url %}<li><a href="{{ add_url }}" target="_blank">{% if add_label %}{{ add_label }}{% else %}Add{% endif %}</a></li>{% endif %}
      {% if list_url %}<li><a href="{{ list_url }}" target="_blank">{% if list_label %}{{ list_label }}{% else %}List{% endif %}</a></li>{% endif %}
    </ul>
  </div>
</div>

{% endif %}
{% endif %}

cshcsite/templates/core/_committee_member.html
{% comment %}
Reusable snippet for a committee member's profile.

Expects two parameters, 'role' and 'role_name'
{% endcomment %}

<a class="captain-link" href="{{ role.member.get_absolute_url }}">
    <div class="media">
        <div class="pull-left media-object">
            {% include 'members/_profile_pic_thumbnail.html' with member=role.member %}
        </div>
        <div class="media-body">
            <h4 class="media-heading">{{ role.member }}</h4>
            <p>{{ role_name }}</p>
        </div>
    </div>
</a>

cshcsite/templates/core/_footer_contact.html
{% url 'contact_us' as contact_us %}
<div class="span3 footer-link">
	<a href="{{ contact_us }}" title="Contact us">
        <div class="pull-left icon"><i class="icon icon-envelope"></i></div>
        <p>Don't be shy<br/><span class="em">Contact Us</span></p>
    </a>
</div>

cshcsite/templates/core/_footer_dir.html
{% url 'directions' as directions %}
<div class="offset1 span3 footer-link">
    <a href="{{ directions }}" title="Directions to our pitch and club house">
        <div class="pull-left icon"><i class="icon icon-map-marker"></i></div>
        <p>Where are we?<br/><span class="em">Find us!</span></p>
    </a>
</div>

cshcsite/templates/core/_home_page_banner.html
{% comment %}
This template encapsulates the top home page banner section.
The top banner style can be modified by the value of the 'HomePageBanner'
ClubInfo database item. Currently the supported values are:
    - 'default': displays latest results and next fixtures
    - 'summer': displays an advert for Summer Hockey
{% endcomment %}

{% url 'match_report_rss_feed' as matches_rss %}
{% url 'calendar' as calendar %}

{% url 'venue_detail' 'wilberforce-road' as uni_url %}


<div id="top-banner" class="{{ banner_style }}">
    <div class="container">
        <div class="row">
            {% if banner_style == 'summer' %}
                <div class="span6">
                    <div class="banner-box sick">
                        <img align="left" class="main left" src="{{ STATIC_URL }}media/Web%20site%20images/sick.png"/>
                        <h3>Sick of the summer...?</h3>
                        <ul>
                            <li>Queezy from too many BBQ burgers and glasses of Pimms?</li>
                            <li>England's World Cup performance made you want to puke?</li>
                            <li>Inverse Seasonal Affective Disorder?</li>
                        </ul>
                    </div>
                </div>
                <div class="span6">
                    <div class="banner-box cure">
                        <img align="right" class="main right" src="{{ STATIC_URL }}media/Web%20site%20images/feel_good.png"/>
                        <p class="lead">Then we prescribe a healthy dose of...</p>
                        <h3 class="title">Summer Hockey!</h3>
                        <h4>Instructions:</h4>
                        <ul>
                            <li>To be taken once a week on <strong>Tuesdays</strong> from <strong>8-9pm</strong></li>
                            <li>Always follow treatment with an hour in the pub</li>
                            <li>Visit your Summer Hockey treatment centre at <strong><a href="{{ uni_url }}">Wilberforce Road</a></strong></li>
                        </ul>
                    </div>
                </div>
            {% else %}
                <div class="span6">
                    <div class="banner-box">
                        <span class="pull-right">
                            <a href="{{ matches_rss }}" title="Subscribe to Cambridge South match reports" target="_blank" class="btn btn-small btn-warning">
                                <i class="icon-rss"></i>Subscribe
                            </a>
                        </span>
                        <h3 id="latest-results">Latest Results</h3>
                        {% include "matches/_latest_results.html" %}
                    </div>
                </div>

                <div class="span6">
                    <div class="banner-box">
                        <span class="pull-right">
                            <a href="{{ calendar }}" title="Import match details into your own calendar" class="btn btn-small btn-primary">
                                <i class="icon-calendar"></i>Calendar
                            </a>
                        </span>
                        <h3 id="next-fixtures">Next Fixtures</h3>
                        {% include "matches/_next_fixtures.html" %}
                    </div>
                </div>
            {% endif %}
        </div>
    </div>
</div>

cshcsite/templates/core/_messages.html
{% comment %}
This snippet renders any messages from the context as alert boxes
{% endcomment %}

{# Messages #}
<div class="messages">
{% if messages %}
    {% for message in messages %}
        <div class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %}">{{ message|safe }}</div>
    {% endfor %}
{% endif %}
</div>

cshcsite/templates/core/_recent_articles.html
<ul class="media-list">
{% for entry in entries %}
    <li class="media">
        <a class="pull-left" title="{{ entry.title }}" href="{{ entry.get_absolute_url }}">
            {% load thumbnail %}
            {% if entry.image %}
                {% thumbnail entry.image "150x100" crop="center" as im %}
                    <img class="article-pic" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}">
                {% endthumbnail %}
            {% else %}
                {% with absolute_static_url|add:'media/placeholder.png' as img_path %}
                    {% thumbnail img_path "150x100" crop="center" as placeholder %}
                        <img class="article-pic" src="{{ placeholder.url }}" width="{{ placeholder.width }}" height="{{ placeholder.height }}">
                    {% endthumbnail %}
                {% endwith %}
            {% endif %}
        </a>
        <div class="media-body">
            <a href="{{ entry.get_absolute_url }}" title="{{ entry.title }}">
                <h4 class="media-heading">{{ entry.title }}</h4>
            </a>
            <p>{{ entry.content|safe|linebreaks|truncatewords_html:40 }}</p>
        </div>
    </li>
    {% empty %}
    <p class="lead">No articles yet.</p>
{% endfor %}
</ul>

cshcsite/templates/core/contact.html
{% extends "base.html" %}

{% comment %}
Form used to email a message to the club secretary
{% endcomment %}

{% block title %}{{ block.super }} | Contact Us{% endblock %}

{% block body_id %}contact-us{% endblock body_id %}

{% block content %}

{% url 'upcoming_trainingsession_list' as training %}
{% url 'contact_us' as contact_us %}

<div id="contact">
    <div class="page-header">
        <h1><i class="icon-envelope"></i>We'd like to hear from you</h1>
    </div>
    <div class="row">
        <div class="span5">
        <p class="lead">We are always looking for new players, whether experienced or new to the sport!</p>
        <p>If you're interested in playing hockey with us, whether casually or competitively, or would just like more information about the club, simply fill in this form. Joining the club mailing lists means you will receive email alerts about games, training, socials etc.</p>
        <p>Alternatively, come along to our evening <a href="{{ training }}">club training</a> and introduce yourself.</p>
        </div>
        <div class="span7">
            <form class="cshc-form" action="{{ contact_us }}" method="post">{% csrf_token %}

                {{ form.first_name.errors }}
                <label for="id_first_name" class="control-label required"></label>
                <input id="id_first_name" maxlength="255" name="first_name" class="name" type="text" placeholder="First name*">

                {{ form.last_name.errors }}
                <label for="id_last_name" class="control-label required"></label>
                <input id="id_last_name" maxlength="255" name="last_name" class="name" type="text" placeholder="Last name*">

                {{ form.email.errors }}
                <label for="id_email" class="control-label required"></label>
                <input id="id_email" maxlength="254" name="email" class="mail" type="text" placeholder="Email*">

                {{ form.phone.errors }}
                <label for="id_phone" class="control-label"></label>
                <input id="id_phone" maxlength="25" name="phone" class="phone" type="text" placeholder="Phone">

                {{ form.message.errors }}
                <label for="id_message" class="control-label required"></label>
                <textarea id="id_message" name="message" placeholder="Message*"></textarea>

                {{ form.mailing_list.errors }}
                <label class="control-label checkbox">
                    <input id="id_mailing_list" name="mailing_list" type="checkbox"> I would like to join the Club mailing lists
                </label>
                
                {% if form.errors.captcha %}{{ form.errors.captcha }}{% endif %}
                {{ form.captcha }}

                <input class="btn btn-primary" type="submit" value="Send your message">
                <p class="required">* required fields</p>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

cshcsite/templates/core/social.html
{% extends "base.html" %}
{% load core_tags %}

{% comment %}
Static page with info about social activities.
{% endcomment %}

{% block title %}{{ block.super }} | Social{% endblock %}

{% block body_id %}social{% endblock body_id %}

{% block content %}

{% comment %}
Facebook Page Embed
Ref: https://developers.facebook.com/docs/plugins/page-plugin
{% endcomment %}
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.4&appId=224662550925394";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



{% get_clubinfo 'MaleSocialSecName' as male_social_sec_name %}
{% get_clubinfo 'FemaleSocialSecName' as female_social_sec_name %}
{% url 'calendar' as calendar %}

<ul class="breadcrumb">
  <li><a href="/">Home</a> <span class="divider">/</span></li>
  <li class="active">Social</li>
</ul>

<div class="page-header">
    <h1>Social Events</h1>
</div>
<p>Cambridge South is a very friendly and sociable club. Keep an eye on your emails and the <a href="{{ calendar }}">calendar</a> for information about forthcoming events. With our super Social (and super-sociable) Secretaries, {{ female_social_sec_name }} and {{ male_social_sec_name }},
there&#39;s sure to be some exciting events in the near future.</p>

<p>You can also read about previous socials on our <a href="/blog/categories/social/">blog</a>.</p>
<h3>Upcoming events</h3>
<p>Club socials are usually posted on our <a href="http://groupspaces.com/cambridgesouthhockeyclub" target="_blank">GroupSpaces page</a>. This is where you can tell us you're coming and buy tickets if required.</p>
<script type="text/javascript" src="http://groupspaces.com/cambridgesouthhockeyclub/api/api.js?wid=654"></script><noscript><a href="http://groupspaces.com/cambridgesouthhockeyclub/calendar">View Calendar</a></noscript>
<h3>Cambridge South's Facebook Page</h3>
<p>Why not 'Like' our <a href="https://www.facebook.com/cambridgesouthhc" target="_blank">Facebook page</a>? We typically use this to post details of social events.</p>
<div class="fb-page" data-href="https://www.facebook.com/cambridgesouthhc" data-width="500" data-height="1000" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true" data-show-posts="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/cambridgesouthhc"><a href="https://www.facebook.com/cambridgesouthhc">Cambridge South Hockey Club</a></blockquote></div></div>
{% endblock %}